/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#include <freertos/FreeRTOS.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ;
typedef struct tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__JeohwCvpfLEpSkpKAlbnrg tySequence__JeohwCvpfLEpSkpKAlbnrg;
typedef struct tySequence__JeohwCvpfLEpSkpKAlbnrg_Content tySequence__JeohwCvpfLEpSkpKAlbnrg_Content;
typedef struct tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI16 align;
NI16 depth;
NU32* display;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__JeohwCvpfLEpSkpKAlbnrg {
  NI len; tySequence__JeohwCvpfLEpSkpKAlbnrg_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__JeohwCvpfLEpSkpKAlbnrg trace;
Exception* up;
};
struct tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw {  Exception Sup;};
struct tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ {  tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw Sup;NI32 errorCode;
};
struct tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__JeohwCvpfLEpSkpKAlbnrg_Content_PP
#define tySequence__JeohwCvpfLEpSkpKAlbnrg_Content_PP
struct tySequence__JeohwCvpfLEpSkpKAlbnrg_Content { NI cap; tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size__LZn6dneMVUSD9cVJcoc7Slw, NI alignment__eu9b1Xf7SGvOM5v8REyXVWA);
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g);
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i__j5Wg6rSPK6jprzM9co5KfZA, NI64 a__U8TO0Zlwhw51KAyAvquExw, NI64 b__hut4c5oxPM3l5OQ8nIwqqg);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str__1hBypH3GHj7R9aGZBu1HZPg);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space__9cQ1OhOryhnk7At3WzUsjtA);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e__9ajCQKqHfiAQicU4Xo4XCfQ, NCSTRING ename__dYYaKlNlIXrIQDE0zrUqCg, NCSTRING procname__0KbbVdUBSy9cVZFkcqkrAbA, NCSTRING filename__OtHzFRym9aG7oNwlVo9bTRVA, NI line__eII5zX9cu2R26e0hzCzdeKQ);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_29)(NimStringV2* dest__C2JKGPCNdWKCPrsQvNywTQ);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
static N_INLINE(void, popFrame)(void);
extern TNimTypeV2 NTIv2__5dAzkrwn5oafhWPCCcILLQ_;
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__KDybzinjxZ9bYLUcaKcpPFQ_2 = { 7 | NIM_STRLIT_FLAG, "error: " };
static const NimStringV2 TM__KDybzinjxZ9bYLUcaKcpPFQ_3 = {7, (NimStrPayload*)&TM__KDybzinjxZ9bYLUcaKcpPFQ_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4298;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;

#line 8 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {	void* T1_;
#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));}

#line 1965 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"

#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}

#line 94 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g) {{
#line 95 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
	{		NI TM__KDybzinjxZ9bYLUcaKcpPFQ_4;		NI TM__KDybzinjxZ9bYLUcaKcpPFQ_5;
#line 95 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		if (!(((NI)0) < src__369aqaoei6FUsRf9cDAsKQ2g.len)) goto LA3_;

#line 97 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"

#line 97 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		if (nimAddInt(src__369aqaoei6FUsRf9cDAsKQ2g.len, ((NI)1), &TM__KDybzinjxZ9bYLUcaKcpPFQ_4)) { raiseOverflow(); goto BeforeRet_;		};		if (((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4)) < ((NI)0) || ((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4), ((NI)0), ((NI)2147483647)); goto BeforeRet_;		}
#line 97 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		copyMem__system_1752(((void*) ((&(*(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).p).data[(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len]))), ((void*) ((&(*src__369aqaoei6FUsRf9cDAsKQ2g.p).data[((NI)0)]))), ((NI) ((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4))));

#line 98 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		if (nimAddInt((*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len, src__369aqaoei6FUsRf9cDAsKQ2g.len, &TM__KDybzinjxZ9bYLUcaKcpPFQ_5)) { raiseOverflow(); goto BeforeRet_;		};		(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len = (NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_5);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	
#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4298);	return result;}

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 41 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, doCheck__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_91)(NI32 ret__2m9cRyGpkDK2tiYARF9amKrg) {NIM_BOOL* nimErr_;	nimfr_("doCheck", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");{nimErr_ = nimErrorFlag();
#line 42 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	nimln_(42, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");	{		
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
NimStringV2 colontmpD_;		tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ* T6_;		NimStringV2 T7_;		NCSTRING T8_;
#line 42 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 42 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		if (!!((ret__2m9cRyGpkDK2tiYARF9amKrg == ((NI32)0)))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;		T6_ = NIM_NIL;		T6_ = (tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ*) nimNewObj(sizeof(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ), NIM_ALIGNOF(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ));		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__5dAzkrwn5oafhWPCCcILLQ_);		(*T6_).Sup.Sup.name = "OSError";
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		nimln_(43, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");		T7_.len = 0; T7_.p = NIM_NIL;
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		T8_ = (NCSTRING)0;		T8_ = esp_err_to_name(ret__2m9cRyGpkDK2tiYARF9amKrg);		colontmpD_ = cstrToNimstr(T8_);		T7_ = rawNewString(colontmpD_.len + 7);appendString((&T7_), TM__KDybzinjxZ9bYLUcaKcpPFQ_3);appendString((&T7_), colontmpD_);		(*T6_).Sup.Sup.message = T7_;		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		raiseExceptionEx((Exception*)T6_, "OSError", "doCheck", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim", 43);goto LA5_;		{			LA5_:;		}
		{
#line 25 "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim"
			nimln_(25, "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim");
#line 25 "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim"
			eqdestroy___stdZassertions_29((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();}

#line 18 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(NU32, toTicks__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_43)(NU64 ts__kperKkENPIQa9bAR1eRwrkw) {	
#line 18 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
NU32 result;	nimfr_("toTicks", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");{	result = (NU32)0;
#line 19 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	nimln_(19, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");
#line 18 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	nimln_(18, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");
#line 19 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	nimln_(19, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");
#line 19 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	result = (NU32)((NU32)(((NU32) (ts__kperKkENPIQa9bAR1eRwrkw))) / (NU32)(portTICK_PERIOD_MS));	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}
