/* Generated by Nim Compiler v1.6.12 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i, NI n);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_5032)(void);
static N_INLINE(void, popFrame)(void);
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;

#line 90 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s) {	NCSTRING result;	result = (NCSTRING)0;
#line 91 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
	{
#line 91 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
		if (!(s.len == ((NI) 0))) goto LA3_;

#line 91 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
		result = "";	}
	goto LA1_;
	LA3_: ;
	{
#line 92 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
		result = ((NCSTRING) ((*s.p).data));	}
	LA1_: ;
	return result;}

#line 549 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!(framePtr__system_4513 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_4513).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	(*s).prev = framePtr__system_4513;
#line 557 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = s;
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		callDepthLimitReached__system_5032();
	}
	LA8_: ;
}

#line 99 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = (*framePtr__system_4513).prev;}

#line 805 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0) {	size_t T5_;	int T6_;	nimfr_("echoBinSafe", "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim");{	{		NimStringV2* s;		NI i;		s = (NimStringV2*)0;
#line 8 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim"
		nimln_(8, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim");		i = ((NI) 0);		{
#line 9 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim"
			nimln_(9, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim");			while (1) {				size_t T4_;				NI TM__MnCJ0VAmeZ9aTATUB39cx60Q_2;
#line 9 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim"

#line 9 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim"
				if (!(i < argsLen_0)) goto LA3;

#line 819 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
				nimln_(819, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim");				if (i < 0 || i >= argsLen_0){ raiseIndexError2(i,argsLen_0-1); goto BeforeRet_;}				s = (&args[i]);
#line 819 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"

#line 819 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"

#line 823 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
				nimln_(823, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim");
#line 819 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
				nimln_(819, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim");				T4_ = (size_t)0;				T4_ = fwrite(((void*) (nimToCStringConv((*s)))), ((size_t) ((*s).len)), ((size_t) 1), stdout);				(void)(T4_);

#line 11 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim"
				nimln_(11, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators.nim");				if (nimAddInt(i, ((NI) 1), &TM__MnCJ0VAmeZ9aTATUB39cx60Q_2)) { raiseOverflow(); goto BeforeRet_;};				i = (NI)(TM__MnCJ0VAmeZ9aTATUB39cx60Q_2);			} LA3: ;
		}
	}

#line 825 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
	nimln_(825, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim");
#line 825 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"

#line 825 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
	T5_ = (size_t)0;	T5_ = fwrite(((void*) ("\012")), ((size_t) 1), ((size_t) 1), stdout);	(void)(T5_);

#line 826 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
	nimln_(826, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim");
#line 826 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"

#line 826 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/io.nim"
	T6_ = (int)0;	T6_ = fflush(stdout);	(void)(T6_);
	}BeforeRet_: ;
	popFrame();}
