/* Generated by Nim Compiler v1.6.12 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#include "freertos/FreeRTOS.h"
#include <freertos/FreeRTOS.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_OSError__Nfkunlq1qr9bu2ay4m6X1Tg tyObject_OSError__Nfkunlq1qr9bu2ay4m6X1Tg;
typedef struct tyObject_CatchableError__8AmVedp6GdHs9chdWk9aTnyw tyObject_CatchableError__8AmVedp6GdHs9chdWk9aTnyw;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__bEnalXJ7iKBtfuz9cMBHCeA tySequence__bEnalXJ7iKBtfuz9cMBHCeA;
typedef struct tySequence__bEnalXJ7iKBtfuz9cMBHCeA_Content tySequence__bEnalXJ7iKBtfuz9cMBHCeA_Content;
typedef struct tyObject_StackTraceEntry__wPpqw4OpnJEig7MVrmxjJw tyObject_StackTraceEntry__wPpqw4OpnJEig7MVrmxjJw;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI align;
NCSTRING name;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {TNimTypeV2* m_type;};
struct tySequence__bEnalXJ7iKBtfuz9cMBHCeA {
  NI len; tySequence__bEnalXJ7iKBtfuz9cMBHCeA_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__bEnalXJ7iKBtfuz9cMBHCeA trace;
Exception* up;
};
struct tyObject_CatchableError__8AmVedp6GdHs9chdWk9aTnyw {  Exception Sup;};
struct tyObject_OSError__Nfkunlq1qr9bu2ay4m6X1Tg {  tyObject_CatchableError__8AmVedp6GdHs9chdWk9aTnyw Sup;NI32 errorCode;
};
struct tyObject_StackTraceEntry__wPpqw4OpnJEig7MVrmxjJw {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__bEnalXJ7iKBtfuz9cMBHCeA_Content_PP
#define tySequence__bEnalXJ7iKBtfuz9cMBHCeA_Content_PP
struct tySequence__bEnalXJ7iKBtfuz9cMBHCeA_Content { NI cap; tyObject_StackTraceEntry__wPpqw4OpnJEig7MVrmxjJw data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size, NI alignment);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source_0, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e, NCSTRING ename, NCSTRING procname, NCSTRING filename, NI line);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_3533)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_5032)(void);
static N_INLINE(void, popFrame)(void);
extern TNimTypeV2 NTIv2__Nfkunlq1qr9bu2ay4m6X1Tg_;
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__KDybzinjxZ9bYLUcaKcpPFQ_2 = { 7 | NIM_STRLIT_FLAG, "error: " };
static const NimStringV2 TM__KDybzinjxZ9bYLUcaKcpPFQ_3 = {7, (NimStrPayload*)&TM__KDybzinjxZ9bYLUcaKcpPFQ_2};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4861;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;

#line 8 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest, void* source_0, NI size) {	void* T1_;
#line 10 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"

#line 10 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest, source_0, ((size_t) (size)));}

#line 2220 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system.nim"
static N_INLINE(void, copyMem__system_1709)(void* dest, void* source_0, NI size) {
#line 2221 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system.nim"

#line 2221 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system.nim"
	nimCopyMem(dest, source_0, size);
}

#line 94 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {{
#line 95 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
	{		NI TM__KDybzinjxZ9bYLUcaKcpPFQ_4;		NI TM__KDybzinjxZ9bYLUcaKcpPFQ_5;
#line 95 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
		if (!(((NI) 0) < src.len)) goto LA3_;

#line 97 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"

#line 97 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
		if (nimAddInt(src.len, ((NI) 1), &TM__KDybzinjxZ9bYLUcaKcpPFQ_4)) { raiseOverflow(); goto BeforeRet_;};		if (((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4)) < ((NI) 0) || ((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4)) > ((NI) 2147483647)){ raiseRangeErrorI((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}
#line 97 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
		copyMem__system_1709(((void*) ((&(*(*dest).p).data[(*dest).len]))), ((void*) ((&(*src.p).data[((NI) 0)]))), ((NI) ((NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_4))));

#line 98 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/strs_v2.nim"
		if (nimAddInt((*dest).len, src.len, &TM__KDybzinjxZ9bYLUcaKcpPFQ_5)) { raiseOverflow(); goto BeforeRet_;};		(*dest).len = (NI)(TM__KDybzinjxZ9bYLUcaKcpPFQ_5);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 423 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4861);	return result;}

#line 549 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!(framePtr__system_4513 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_4513).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	(*s).prev = framePtr__system_4513;
#line 557 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = s;
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		callDepthLimitReached__system_5032();
	}
	LA8_: ;
}

#line 99 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = (*framePtr__system_4513).prev;}

#line 41 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, doCheck__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZgeneral_78)(NI32 ret) {NIM_BOOL* nimErr_;	nimfr_("doCheck", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim");{nimErr_ = nimErrorFlag();
#line 42 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
	nimln_(42, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim");	{		NimStringV2 colontmpD_;		tyObject_OSError__Nfkunlq1qr9bu2ay4m6X1Tg* T6_;		NimStringV2 T7_;		NCSTRING T8_;
#line 42 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"

#line 42 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
		if (!!((ret == ((NI32) 0)))) goto LA3_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;		T6_ = NIM_NIL;		T6_ = (tyObject_OSError__Nfkunlq1qr9bu2ay4m6X1Tg*) nimNewObj(sizeof(tyObject_OSError__Nfkunlq1qr9bu2ay4m6X1Tg), NIM_ALIGNOF(tyObject_OSError__Nfkunlq1qr9bu2ay4m6X1Tg));		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__Nfkunlq1qr9bu2ay4m6X1Tg_);		(*T6_).Sup.Sup.name = "OSError";
#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
		nimln_(43, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim");		T7_.len = 0; T7_.p = NIM_NIL;
#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
		T8_ = (NCSTRING)0;		T8_ = esp_err_to_name(ret);		colontmpD_ = cstrToNimstr(T8_);		T7_ = rawNewString(colontmpD_.len + 7);appendString((&T7_), TM__KDybzinjxZ9bYLUcaKcpPFQ_3);appendString((&T7_), colontmpD_);		(*T6_).Sup.Sup.message = T7_;		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
		raiseExceptionEx((Exception*)T6_, "OSError", "doCheck", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim", 43);		goto LA5_;		{			LA5_:;		}
		{
#line 54 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/fatal.nim"
			nimln_(54, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/fatal.nim");
#line 54 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/fatal.nim"
			eqdestroy___system_3533((&colontmpD_));
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();}

#line 18 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(NU32, toTicks__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZgeneral_37)(NU64 ts) {	NU32 result;	nimfr_("toTicks", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim");{	result = (NU32)0;
#line 19 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
	nimln_(19, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim");
#line 19 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"

#line 19 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/general.nim"
	result = (NU32)((NU32)(((NU32) (ts))) / (NU32)(portTICK_PERIOD_MS));	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}
