/* Generated by Nim Compiler v1.6.12 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include "soc/io_mux_reg.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_5032)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE NI GPIO_PIN_REG0__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_213;
N_LIB_PRIVATE NI GPIO_PIN_REG1__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_214;
N_LIB_PRIVATE NI GPIO_PIN_REG2__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_215;
N_LIB_PRIVATE NI GPIO_PIN_REG3__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_216;
N_LIB_PRIVATE NI GPIO_PIN_REG4__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_217;
N_LIB_PRIVATE NI GPIO_PIN_REG5__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_218;
N_LIB_PRIVATE NI GPIO_PIN_REG6__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_219;
N_LIB_PRIVATE NI GPIO_PIN_REG7__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_220;
N_LIB_PRIVATE NI GPIO_PIN_REG8__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_221;
N_LIB_PRIVATE NI GPIO_PIN_REG9__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_222;
N_LIB_PRIVATE NI GPIO_PIN_REG10__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_223;
N_LIB_PRIVATE NI GPIO_PIN_REG11__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_224;
N_LIB_PRIVATE NI GPIO_PIN_REG12__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_225;
N_LIB_PRIVATE NI GPIO_PIN_REG13__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_226;
N_LIB_PRIVATE NI GPIO_PIN_REG14__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_227;
N_LIB_PRIVATE NI GPIO_PIN_REG15__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_228;
N_LIB_PRIVATE NI GPIO_PIN_REG16__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_229;
N_LIB_PRIVATE NI GPIO_PIN_REG17__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_230;
N_LIB_PRIVATE NI GPIO_PIN_REG18__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_231;
N_LIB_PRIVATE NI GPIO_PIN_REG19__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_232;
N_LIB_PRIVATE NI GPIO_PIN_REG20__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_233;
N_LIB_PRIVATE NI GPIO_PIN_REG21__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_234;
N_LIB_PRIVATE NI GPIO_PIN_REG22__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_235;
N_LIB_PRIVATE NI GPIO_PIN_REG23__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_236;
N_LIB_PRIVATE NI GPIO_PIN_REG25__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_237;
N_LIB_PRIVATE NI GPIO_PIN_REG26__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_238;
N_LIB_PRIVATE NI GPIO_PIN_REG27__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_239;
N_LIB_PRIVATE NI GPIO_PIN_REG32__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_240;
N_LIB_PRIVATE NI GPIO_PIN_REG33__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_241;
N_LIB_PRIVATE NI GPIO_PIN_REG34__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_242;
N_LIB_PRIVATE NI GPIO_PIN_REG35__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_243;
N_LIB_PRIVATE NI GPIO_PIN_REG36__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_244;
N_LIB_PRIVATE NI GPIO_PIN_REG37__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_245;
N_LIB_PRIVATE NI GPIO_PIN_REG38__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_246;
N_LIB_PRIVATE NI GPIO_PIN_REG39__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_247;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;

#line 549 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!(framePtr__system_4513 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_4513).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	(*s).prev = framePtr__system_4513;
#line 557 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = s;
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		callDepthLimitReached__system_5032();
	}
	LA8_: ;
}

#line 99 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = (*framePtr__system_4513).prev;}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnesperminusathdevelatsnesperatsespatsdriveratsgpio_driverdotnim_Init000)(void) {

#line 999999 "generated_not_to_break_here"
{
	nimfr_("gpio_driver", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");
#line 163 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(163, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG0__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_213 = IO_MUX_GPIO0_REG;
#line 164 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(164, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG1__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_214 = IO_MUX_GPIO1_REG;
#line 165 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(165, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG2__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_215 = IO_MUX_GPIO2_REG;
#line 166 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(166, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG3__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_216 = IO_MUX_GPIO3_REG;
#line 167 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(167, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG4__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_217 = IO_MUX_GPIO4_REG;
#line 168 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(168, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG5__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_218 = IO_MUX_GPIO5_REG;
#line 169 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(169, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG6__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_219 = IO_MUX_GPIO6_REG;
#line 170 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(170, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG7__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_220 = IO_MUX_GPIO7_REG;
#line 171 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(171, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG8__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_221 = IO_MUX_GPIO8_REG;
#line 172 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(172, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG9__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_222 = IO_MUX_GPIO9_REG;
#line 173 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(173, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG10__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_223 = IO_MUX_GPIO10_REG;
#line 174 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(174, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG11__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_224 = IO_MUX_GPIO11_REG;
#line 175 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(175, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG12__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_225 = IO_MUX_GPIO12_REG;
#line 176 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(176, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG13__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_226 = IO_MUX_GPIO13_REG;
#line 177 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(177, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG14__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_227 = IO_MUX_GPIO14_REG;
#line 178 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(178, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG15__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_228 = IO_MUX_GPIO15_REG;
#line 179 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(179, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG16__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_229 = IO_MUX_GPIO16_REG;
#line 180 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(180, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG17__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_230 = IO_MUX_GPIO17_REG;
#line 181 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(181, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG18__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_231 = IO_MUX_GPIO18_REG;
#line 182 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(182, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG19__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_232 = IO_MUX_GPIO19_REG;
#line 183 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(183, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG20__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_233 = IO_MUX_GPIO20_REG;
#line 184 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(184, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG21__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_234 = IO_MUX_GPIO21_REG;
#line 185 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(185, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG22__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_235 = IO_MUX_GPIO22_REG;
#line 186 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(186, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG23__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_236 = IO_MUX_GPIO23_REG;
#line 187 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(187, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG25__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_237 = IO_MUX_GPIO25_REG;
#line 188 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(188, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG26__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_238 = IO_MUX_GPIO26_REG;
#line 189 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(189, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG27__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_239 = IO_MUX_GPIO27_REG;
#line 190 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(190, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG32__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_240 = IO_MUX_GPIO32_REG;
#line 191 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(191, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG33__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_241 = IO_MUX_GPIO33_REG;
#line 192 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(192, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG34__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_242 = IO_MUX_GPIO34_REG;
#line 193 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(193, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG35__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_243 = IO_MUX_GPIO35_REG;
#line 194 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(194, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG36__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_244 = IO_MUX_GPIO36_REG;
#line 195 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(195, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG37__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_245 = IO_MUX_GPIO37_REG;
#line 196 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(196, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG38__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_246 = IO_MUX_GPIO38_REG;
#line 197 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim"
	nimln_(197, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp/driver/gpio_driver.nim");	GPIO_PIN_REG39__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZespZdriverZgpio95driver_247 = IO_MUX_GPIO39_REG;	popFrame();}
}

