/* Generated by Nim Compiler v1.6.12 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <i2cdev.h>
#include <string.h>
#include "esp_log.h"
#include "driver/i2c.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef NU8 tyArray__bN9bddWn8oiNSHn2MqEJSZQ[2];
typedef NI32 tyEnum_i2c_mode_t__PgYhFwzRJufT7Fogkw6b9cw;
typedef NI32 tyEnum_gpio_num_t__Av9au5ixmjPr8CeBJERkCvw;
N_LIB_PRIVATE N_NIMCALL(void, i2cDeviceInit__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZesp45idf45libZi50cdev95utils_25)(void);
N_LIB_PRIVATE N_NIMCALL(void, doCheck__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZgeneral_78)(NI32 ret);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_5032)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, nimZeroMem)(void* p, NI size);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size);
N_LIB_PRIVATE NIM_BOOL i2cStarted__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZesp45idf45libZi50cdev95utils_24;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4861;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;

#line 423 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4861);	return result;}

#line 549 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!(framePtr__system_4513 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_4513).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	(*s).prev = framePtr__system_4513;
#line 557 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = s;
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		callDepthLimitReached__system_5032();
	}
	LA8_: ;
}

#line 99 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = (*framePtr__system_4513).prev;}

#line 34 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
N_LIB_PRIVATE N_NIMCALL(void, i2cDeviceInit__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZesp45idf45libZi50cdev95utils_25)(void) {NIM_BOOL* nimErr_;	nimfr_("i2cDeviceInit", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");{nimErr_ = nimErrorFlag();
#line 35 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(35, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");	{		NI32 T5_;
#line 35 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		if (!!(i2cStarted__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZesp45idf45libZi50cdev95utils_24)) goto LA3_;

#line 36 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(36, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 36 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 36 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		T5_ = (NI32)0;		T5_ = i2cdev_init();
#line 36 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		doCheck__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZgeneral_78(T5_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();}

#line 19 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a, int v, NI size) {	void* T1_;
#line 21 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"

#line 21 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a, v, ((size_t) (size)));}

#line 30 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p, NI size) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 31 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"

#line 31 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/memory.nim"
	nimSetMem__systemZmemory_7(p, ((int) 0), size);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 41 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
N_LIB_PRIVATE N_NIMCALL(NI32, i2c_read_reg__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZesp45idf45libZi50cdev95utils_26)(i2c_dev_t* dev, NU8 reg, NU8* val) {	NI32 result;	tyArray__bN9bddWn8oiNSHn2MqEJSZQ buf;	NI32 res;	nimfr_("i2c_read_reg", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");{	result = (NI32)0;	nimZeroMem((void*)buf, sizeof(tyArray__bN9bddWn8oiNSHn2MqEJSZQ));
#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(43, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 43 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	res = i2c_dev_read_reg(dev, reg, ((void*) ((&buf[(((NI) 0))- 0]))), ((size_t) 2));
#line 44 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(44, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");	{
#line 44 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 44 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		if (!!((res == ((NI32) 0)))) goto LA3_;

#line 45 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(45, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 45 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		ESP_LOGD("I2CD", "Could not read from register 0x%02x", reg);

#line 46 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(46, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 46 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		result = res;		goto BeforeRet_;
	}
	LA3_: ;

#line 48 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(48, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 48 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 48 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	(*val) = (NU8)((NU8)((NU32)(buf[(((NI) 0))- 0]) << (NU32)(((NI) 8))) | buf[(((NI) 1))- 0]);
#line 49 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(49, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 49 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	result = ((NI32) 0);	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 51 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
N_LIB_PRIVATE N_NIMCALL(NI32, i2c_write_reg__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZesp45idf45libZi50cdev95utils_49)(i2c_dev_t* dev, NU8 reg, NU8 val) {	NI32 result;	tyArray__bN9bddWn8oiNSHn2MqEJSZQ buf;	NI32 res;	nimfr_("i2c_write_reg", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");{	result = (NI32)0;	nimZeroMem((void*)buf, sizeof(tyArray__bN9bddWn8oiNSHn2MqEJSZQ));
#line 52 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(52, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 52 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	buf[0] = (NU8)((NU8)(val) >> (NU32)(((NI) 8)));	buf[1] = val;
#line 53 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(53, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 53 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	res = i2c_dev_write_reg(dev, reg, ((void*) ((&buf[(((NI) 0))- 0]))), ((size_t) 2));
#line 54 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(54, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");	{
#line 54 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 54 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		if (!!((res == ((NI32) 0)))) goto LA3_;

#line 55 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(55, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 55 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		ESP_LOGD("I2CD", "Could not write 0x%04x to register 0x%02x", val, reg);

#line 56 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(56, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 56 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
		result = res;		goto BeforeRet_;
	}
	LA3_: ;

#line 57 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(57, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 57 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	result = ((NI32) 0);	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgsatsnesperminusathdevelatsnesperatsespminusidfminuslibatsi2cdev_utilsdotnim_Init000)(void) {

#line 999999 "generated_not_to_break_here"
{
NIM_BOOL* nimErr_;	nimfr_("i2cdev_utils", "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");nimErr_ = nimErrorFlag();
#line 39 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(39, "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 39 "/home/vincent/.nimble/pkgs/nesper-#devel/nesper/esp-idf-lib/i2cdev_utils.nim"
	i2cDeviceInit__OOZOOZOOZOOZOOZOnimbleZpkgsZnesper4535develZnesperZesp45idf45libZi50cdev95utils_25();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	BeforeRet_: ;
	popFrame();}
}

