/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg;
typedef struct tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg;
typedef struct tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g;
typedef struct tyObject_Defect__j8dL1Y9bprG2UE9bJKmSmTSg tyObject_Defect__j8dL1Y9bprG2UE9bJKmSmTSg;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__JeohwCvpfLEpSkpKAlbnrg tySequence__JeohwCvpfLEpSkpKAlbnrg;
typedef struct tySequence__JeohwCvpfLEpSkpKAlbnrg_Content tySequence__JeohwCvpfLEpSkpKAlbnrg_Content;
typedef struct tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA;
typedef struct tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ;
typedef struct tyTuple__D5XwJS4yba0pRdHRq4pVrw tyTuple__D5XwJS4yba0pRdHRq4pVrw;
typedef struct tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA;
typedef struct tyObject_ArithmeticDefect__YiWOaersyuJOmNv9cJOxAxw tyObject_ArithmeticDefect__YiWOaersyuJOmNv9cJOxAxw;
typedef struct tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ;
typedef struct tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw;
typedef struct tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA;
typedef struct tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw;
struct TNimTypeV2 {void* destructor;
NI size;
NI16 align;
NI16 depth;
NU32* display;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {TNimTypeV2* m_type;};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
struct tySequence__JeohwCvpfLEpSkpKAlbnrg {
  NI len; tySequence__JeohwCvpfLEpSkpKAlbnrg_Content* p;
};
struct Exception {  RootObj Sup;Exception* parent;
NCSTRING name;
NimStringV2 message;
tySequence__JeohwCvpfLEpSkpKAlbnrg trace;
Exception* up;
};
struct tyObject_Defect__j8dL1Y9bprG2UE9bJKmSmTSg {  Exception Sup;};
struct tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g {  tyObject_Defect__j8dL1Y9bprG2UE9bJKmSmTSg Sup;};
struct tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A {NI len;
NI cap;
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ {NI len;
NI cap;
tyTuple__D5XwJS4yba0pRdHRq4pVrw* d;
};
struct tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA {tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A traceStack;
tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ toFree;
NI freed;
NI touched;
NI edges;
NI rcSum;
NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyUncheckedArray__72XmdLy0QAaMtx66AmNKfA[1];
struct tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA {  tyObject_Defect__j8dL1Y9bprG2UE9bJKmSmTSg Sup;};
struct tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg {NI rc;
NI rootIdx;
};
struct tyObject_ArithmeticDefect__YiWOaersyuJOmNv9cJOxAxw {  tyObject_Defect__j8dL1Y9bprG2UE9bJKmSmTSg Sup;};
struct tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg {  tyObject_ArithmeticDefect__YiWOaersyuJOmNv9cJOxAxw Sup;};
struct tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw {  Exception Sup;};
struct tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ {  tyObject_CatchableError__VpuqbGFM5axURcja7FU4zw Sup;NI32 errorCode;
};
struct tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA {  tyObject_ArithmeticDefect__YiWOaersyuJOmNv9cJOxAxw Sup;};
struct tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw {NCSTRING procname;
NI line;
NCSTRING filename;
};


#ifndef tySequence__JeohwCvpfLEpSkpKAlbnrg_Content_PP
#define tySequence__JeohwCvpfLEpSkpKAlbnrg_Content_PP
struct tySequence__JeohwCvpfLEpSkpKAlbnrg_Content { NI cap; tyObject_StackTraceEntry__GlADfPCccOY5svZhqR6srw data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4925)(tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg* dest__0SVougbgzTwtS5BtPjXzjQ);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p__dABzUdgzrkaSDMDdaWLtRg);
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4528)(tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g* dest__0SVougbgzTwtS5BtPjXzjQ_2);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p__9avvNwjq1NdQwdCBwEYwA9bw);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_29)(NimStringV2* dest__C2JKGPCNdWKCPrsQvNywTQ);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_86)(tySequence__JeohwCvpfLEpSkpKAlbnrg* dest__OvUJ7i3R9aE9as9bgGZONrFOA);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4537)(tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g* dest__vCkiftuDKH5sFZLsuJkJYw, void* env__mx0njgyfbnJm7NN9b3EB7xg);
static N_INLINE(void, nimTraceRefDyn)(void* q__DU69bA8QWYzcJYHZK62MWjA, void* env__jq9cK8cvI9c0aQFP3P6pQbYA);
static N_INLINE(void, add__system_2812)(tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A* s__G58rBzp9arUs2Le3q9bajUHA, void** c__glbQoed0fMuhXSt1wQUc7w, TNimTypeV2* t__afUUWAFqIJFXIEkjClESEA);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOCONV(void*, allocSharedImpl)(NI size__PQOom62dq59az26ZBA3l8Lg);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i__j5Wg6rSPK6jprzM9co5KfZA, NI64 a__U8TO0Zlwhw51KAyAvquExw, NI64 b__hut4c5oxPM3l5OQ8nIwqqg);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p__XTVwAD5Qcy8cCUaIcC80hw);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___stdZassertions_95)(tySequence__JeohwCvpfLEpSkpKAlbnrg* dest__MtFFOU2wNRj2y9bA8lUbcdQ, void* env__kESFTih59bdOEL17KGJBDtg);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4585)(tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA* dest__0SVougbgzTwtS5BtPjXzjQ_3);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4594)(tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA* dest__vCkiftuDKH5sFZLsuJkJYw_2, void* env__mx0njgyfbnJm7NN9b3EB7xg_2);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3315)(NIM_BOOL isDestroyAction__wlZkTmY2exyvD4PmYZgCHw, tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg* s__rifrsJGbWaDLWZRj0ktOnA, TNimTypeV2* desc__YB9c2fwKemzor6iGIpZW9bIw);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4934)(tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg* dest__vCkiftuDKH5sFZLsuJkJYw_3, void* env__mx0njgyfbnJm7NN9b3EB7xg_3);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_97)(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ* dest__0SVougbgzTwtS5BtPjXzjQ_4);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_106)(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ* dest__vCkiftuDKH5sFZLsuJkJYw_4, void* env__mx0njgyfbnJm7NN9b3EB7xg_4);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4979)(tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA* dest__0SVougbgzTwtS5BtPjXzjQ_5);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4988)(tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA* dest__vCkiftuDKH5sFZLsuJkJYw_5, void* env__mx0njgyfbnJm7NN9b3EB7xg_5);
N_LIB_PRIVATE TNimTypeV2 NTIv2__sDXWxM9cLtdm57Ktd9a3G3dg_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__kfr8Gk0YW3vN449axL9bRA0g_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__LJca9bbm2fCV5HMfY7J4FwA_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__5dAzkrwn5oafhWPCCcILLQ_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__O8iXngniIQDh5ZM50LpbXA_;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_2[4] = {3701606400, 1285336064, 3343635712, 4210825728};
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
N_LIB_PRIVATE TNimTypeV2 NTIv2__kfr8Gk0YW3vN449axL9bRA0g_ = {.destructor = (void*)eqdestroy___system_4528, .size = sizeof(tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g), .align = (NI16) NIM_ALIGNOF(tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_2, .traceImpl = (void*)eqtrace___system_4537, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_7[4] = {3701606400, 1285336064, 3343635712, 2535127296};
N_LIB_PRIVATE TNimTypeV2 NTIv2__LJca9bbm2fCV5HMfY7J4FwA_ = {.destructor = (void*)eqdestroy___system_4585, .size = sizeof(tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA), .align = (NI16) NIM_ALIGNOF(tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_7, .traceImpl = (void*)eqtrace___system_4594, .flags = 0};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4298;
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_9[5] = {3701606400, 1285336064, 3343635712, 630089984, 903267328};
N_LIB_PRIVATE TNimTypeV2 NTIv2__sDXWxM9cLtdm57Ktd9a3G3dg_ = {.destructor = (void*)eqdestroy___system_4925, .size = sizeof(tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg), .align = (NI16) NIM_ALIGNOF(tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_9, .traceImpl = (void*)eqtrace___system_4934, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_10[4] = {3701606400, 1285336064, 2611637248, 3493040640};
N_LIB_PRIVATE TNimTypeV2 NTIv2__5dAzkrwn5oafhWPCCcILLQ_ = {.destructor = (void*)eqdestroy___OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_97, .size = sizeof(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ), .align = (NI16) NIM_ALIGNOF(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ), .depth = 3, .display = TM__TzI3paKQY09cLjc9cmCvur3A_10, .traceImpl = (void*)eqtrace___OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_106, .flags = 0};
static NIM_CONST NU32 TM__TzI3paKQY09cLjc9cmCvur3A_11[5] = {3701606400, 1285336064, 3343635712, 630089984, 3365379584};
N_LIB_PRIVATE TNimTypeV2 NTIv2__O8iXngniIQDh5ZM50LpbXA_ = {.destructor = (void*)eqdestroy___system_4979, .size = sizeof(tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA), .align = (NI16) NIM_ALIGNOF(tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA), .depth = 4, .display = TM__TzI3paKQY09cLjc9cmCvur3A_11, .traceImpl = (void*)eqtrace___system_4988, .flags = 0};

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4528)(tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g* dest__0SVougbgzTwtS5BtPjXzjQ_2) {
#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T3_;
#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.parent);		if (!T3_) goto LA4_;

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.parent);
	}
	LA4_: ;

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_29((&(*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.message));

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_86((&(*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.trace));

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T8_;
#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.up);		if (!T8_) goto LA9_;

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_2).Sup.Sup.up);
	}
	LA9_: ;
}

#line 8 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {	void* T1_;
#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));}

#line 1965 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"

#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 19 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
static N_INLINE(void, add__system_2812)(tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A* s__G58rBzp9arUs2Le3q9bajUHA, void** c__glbQoed0fMuhXSt1wQUc7w, TNimTypeV2* t__afUUWAFqIJFXIEkjClESEA) {	
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
void** colontmp_;	
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
TNimTypeV2* colontmp__2;	NI TM__TzI3paKQY09cLjc9cmCvur3A_6;	nimfr_("add", "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");{
#line 20 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	nimln_(20, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");	{		NI TM__TzI3paKQY09cLjc9cmCvur3A_3;		
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;		NI TM__TzI3paKQY09cLjc9cmCvur3A_4;		void* T5_;		NI TM__TzI3paKQY09cLjc9cmCvur3A_5;
#line 20 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (!((*s__G58rBzp9arUs2Le3q9bajUHA).cap <= (*s__G58rBzp9arUs2Le3q9bajUHA).len)) goto LA3_;

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(21, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s__G58rBzp9arUs2Le3q9bajUHA).cap, ((NI)3), &TM__TzI3paKQY09cLjc9cmCvur3A_3)) { raiseOverflow(); goto BeforeRet_;		};		(*s__G58rBzp9arUs2Le3q9bajUHA).cap = (NI)((NI)(TM__TzI3paKQY09cLjc9cmCvur3A_3) / ((NI)2));
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(23, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s__G58rBzp9arUs2Le3q9bajUHA).cap, ((NI)8), &TM__TzI3paKQY09cLjc9cmCvur3A_4)) { raiseOverflow(); goto BeforeRet_;		};		if (((NU) ((NI)(TM__TzI3paKQY09cLjc9cmCvur3A_4))) > (NU)(((NI)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;		}
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		T5_ = (void*)0;		T5_ = allocSharedImpl(((NI) (((NU) ((NI)(TM__TzI3paKQY09cLjc9cmCvur3A_4))))));		d = ((tyTuple__N4J9cV4JZGem3ljqqj5rT0Q*) (T5_));
#line 26 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(26, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 26 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s__G58rBzp9arUs2Le3q9bajUHA).len, ((NI)8), &TM__TzI3paKQY09cLjc9cmCvur3A_5)) { raiseOverflow(); goto BeforeRet_;		};		if (((NI)(TM__TzI3paKQY09cLjc9cmCvur3A_5)) < ((NI)0) || ((NI)(TM__TzI3paKQY09cLjc9cmCvur3A_5)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__TzI3paKQY09cLjc9cmCvur3A_5), ((NI)0), ((NI)2147483647)); goto BeforeRet_;		}
#line 26 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		copyMem__system_1752(((void*) (d)), ((void*) ((*s__G58rBzp9arUs2Le3q9bajUHA).d)), ((NI) ((NI)(TM__TzI3paKQY09cLjc9cmCvur3A_5))));

#line 28 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(28, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 28 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		deallocShared(((void*) ((*s__G58rBzp9arUs2Le3q9bajUHA).d)));

#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(31, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		(*s__G58rBzp9arUs2Le3q9bajUHA).d = d;	}
	LA3_: ;

#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	nimln_(33, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");	colontmp_ = c__glbQoed0fMuhXSt1wQUc7w;
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	colontmp__2 = t__afUUWAFqIJFXIEkjClESEA;
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	(*s__G58rBzp9arUs2Le3q9bajUHA).d[(*s__G58rBzp9arUs2Le3q9bajUHA).len].Field0 = colontmp_;	(*s__G58rBzp9arUs2Le3q9bajUHA).d[(*s__G58rBzp9arUs2Le3q9bajUHA).len].Field1 = colontmp__2;
#line 34 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	nimln_(34, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");	if (nimAddInt((*s__G58rBzp9arUs2Le3q9bajUHA).len, ((NI)1), &TM__TzI3paKQY09cLjc9cmCvur3A_6)) { raiseOverflow(); goto BeforeRet_;	};	(*s__G58rBzp9arUs2Le3q9bajUHA).len = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_6);	}BeforeRet_: ;
	popFrame();}

#line 131 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
static N_INLINE(void, nimTraceRefDyn)(void* q__DU69bA8QWYzcJYHZK62MWjA, void* env__jq9cK8cvI9c0aQFP3P6pQbYA) {	
#line 132 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
void** p;	nimfr_("nimTraceRefDyn", "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 132 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(132, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	p = ((void**) (q__DU69bA8QWYzcJYHZK62MWjA));
#line 133 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(133, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	{		
#line 134 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA* j;
#line 133 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 133 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		if (!!(((*p) == NIM_NIL))) goto LA3_;

#line 134 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(134, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");		j = ((tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA*) (env__jq9cK8cvI9c0aQFP3P6pQbYA));
#line 135 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(135, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 135 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		add__system_2812((&(*j).traceStack), p, (*((TNimTypeV2**) ((*p)))));
	}
	LA3_: ;
	popFrame();}

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4537)(tyObject_RangeDefect__kfr8Gk0YW3vN449axL9bRA0g* dest__vCkiftuDKH5sFZLsuJkJYw, void* env__mx0njgyfbnJm7NN9b3EB7xg) {
#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw).Sup.Sup.parent, env__mx0njgyfbnJm7NN9b3EB7xg);

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqtrace___stdZassertions_95((&(*dest__vCkiftuDKH5sFZLsuJkJYw).Sup.Sup.trace), env__mx0njgyfbnJm7NN9b3EB7xg);

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 54 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw).Sup.Sup.up, env__mx0njgyfbnJm7NN9b3EB7xg);
}

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4585)(tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA* dest__0SVougbgzTwtS5BtPjXzjQ_3) {
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T3_;
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.parent);		if (!T3_) goto LA4_;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.parent);
	}
	LA4_: ;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_29((&(*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.message));

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_86((&(*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.trace));

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T8_;
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.up);		if (!T8_) goto LA9_;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_3).Sup.Sup.up);
	}
	LA9_: ;
}

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4594)(tyObject_IndexDefect__LJca9bbm2fCV5HMfY7J4FwA* dest__vCkiftuDKH5sFZLsuJkJYw_2, void* env__mx0njgyfbnJm7NN9b3EB7xg_2) {
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_2).Sup.Sup.parent, env__mx0njgyfbnJm7NN9b3EB7xg_2);

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqtrace___stdZassertions_95((&(*dest__vCkiftuDKH5sFZLsuJkJYw_2).Sup.Sup.trace), env__mx0njgyfbnJm7NN9b3EB7xg_2);

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_2).Sup.Sup.up, env__mx0njgyfbnJm7NN9b3EB7xg_2);
}

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 363 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ) {	
#line 363 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
NI result;	nimfr_("-%", "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");	result = (NI)0;
#line 363 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	nimln_(363, "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");
#line 364 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	nimln_(364, "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");
#line 368 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	nimln_(368, "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU32)(((NU) (x__nhqJNug5PDvy9ah8vc6uJ5Q))) - (NU32)(((NU) (y__LJLJ0MGnpTb2U2nvMvG6MQ))))));	popFrame();	return result;}

#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	
#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4298);	return result;}

#line 477 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p__dABzUdgzrkaSDMDdaWLtRg) {	
#line 477 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("nimDecRefIsLastCyclicDyn", "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 478 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(478, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	{		
#line 479 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg* cell;		NI T5_;
#line 478 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 478 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		if (!!((p__dABzUdgzrkaSDMDdaWLtRg == NIM_NIL))) goto LA3_;

#line 479 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(479, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
		nimln_(43, "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___system_790(((NI) (ptrdiff_t) (p__dABzUdgzrkaSDMDdaWLtRg)), ((NI)8));		cell = ((tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg*) (T5_));
#line 480 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(480, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");		{
#line 480 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 480 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;

#line 481 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			nimln_(481, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 481 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__TzI3paKQY09cLjc9cmCvur3A_8;
#line 484 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			nimln_(484, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");			if (nimSubInt((*cell).rc, ((NI)16), &TM__TzI3paKQY09cLjc9cmCvur3A_8)) { raiseOverflow(); goto BeforeRet_;			};			(*cell).rc = (NI)(TM__TzI3paKQY09cLjc9cmCvur3A_8);		}
		LA6_: ;

#line 486 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(486, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 486 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		rememberCycle__system_3315(result, cell, (*((TNimTypeV2**) (p__dABzUdgzrkaSDMDdaWLtRg))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4925)(tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg* dest__0SVougbgzTwtS5BtPjXzjQ) {
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T3_;
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.parent);		if (!T3_) goto LA4_;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.parent);
	}
	LA4_: ;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_29((&(*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.message));

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_86((&(*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.trace));

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T8_;
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.up);		if (!T8_) goto LA9_;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ).Sup.Sup.Sup.up);
	}
	LA9_: ;
}

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4934)(tyObject_OverflowDefect__sDXWxM9cLtdm57Ktd9a3G3dg* dest__vCkiftuDKH5sFZLsuJkJYw_3, void* env__mx0njgyfbnJm7NN9b3EB7xg_3) {
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_3).Sup.Sup.Sup.parent, env__mx0njgyfbnJm7NN9b3EB7xg_3);

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqtrace___stdZassertions_95((&(*dest__vCkiftuDKH5sFZLsuJkJYw_3).Sup.Sup.Sup.trace), env__mx0njgyfbnJm7NN9b3EB7xg_3);

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_3).Sup.Sup.Sup.up, env__mx0njgyfbnJm7NN9b3EB7xg_3);
}

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_97)(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ* dest__0SVougbgzTwtS5BtPjXzjQ_4) {
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	{		NIM_BOOL T3_;
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_4).Sup.Sup.parent);		if (!T3_) goto LA4_;

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_4).Sup.Sup.parent);
	}
	LA4_: ;

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	eqdestroy___stdZassertions_29((&(*dest__0SVougbgzTwtS5BtPjXzjQ_4).Sup.Sup.message));

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	eqdestroy___stdZassertions_86((&(*dest__0SVougbgzTwtS5BtPjXzjQ_4).Sup.Sup.trace));

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	{		NIM_BOOL T8_;
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_4).Sup.Sup.up);		if (!T8_) goto LA9_;

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_4).Sup.Sup.up);
	}
	LA9_: ;
}

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_106)(tyObject_OSError__5dAzkrwn5oafhWPCCcILLQ* dest__vCkiftuDKH5sFZLsuJkJYw_4, void* env__mx0njgyfbnJm7NN9b3EB7xg_4) {
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_4).Sup.Sup.parent, env__mx0njgyfbnJm7NN9b3EB7xg_4);

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	eqtrace___stdZassertions_95((&(*dest__vCkiftuDKH5sFZLsuJkJYw_4).Sup.Sup.trace), env__mx0njgyfbnJm7NN9b3EB7xg_4);

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"

#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_4).Sup.Sup.up, env__mx0njgyfbnJm7NN9b3EB7xg_4);
}

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___system_4979)(tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA* dest__0SVougbgzTwtS5BtPjXzjQ_5) {
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T3_;
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_5).Sup.Sup.Sup.parent);		if (!T3_) goto LA4_;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_5).Sup.Sup.Sup.parent);
	}
	LA4_: ;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_29((&(*dest__0SVougbgzTwtS5BtPjXzjQ_5).Sup.Sup.Sup.message));

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqdestroy___stdZassertions_86((&(*dest__0SVougbgzTwtS5BtPjXzjQ_5).Sup.Sup.Sup.trace));

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	{		NIM_BOOL T8_;
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		T8_ = (NIM_BOOL)0;		T8_ = nimDecRefIsLastCyclicDyn((*dest__0SVougbgzTwtS5BtPjXzjQ_5).Sup.Sup.Sup.up);		if (!T8_) goto LA9_;

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
		nimDestroyAndDispose((*dest__0SVougbgzTwtS5BtPjXzjQ_5).Sup.Sup.Sup.up);
	}
	LA9_: ;
}

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___system_4988)(tyObject_DivByZeroDefect__O8iXngniIQDh5ZM50LpbXA* dest__vCkiftuDKH5sFZLsuJkJYw_5, void* env__mx0njgyfbnJm7NN9b3EB7xg_5) {
#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_5).Sup.Sup.Sup.parent, env__mx0njgyfbnJm7NN9b3EB7xg_5);

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	eqtrace___stdZassertions_95((&(*dest__vCkiftuDKH5sFZLsuJkJYw_5).Sup.Sup.Sup.trace), env__mx0njgyfbnJm7NN9b3EB7xg_5);

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"

#line 51 "/home/vincent/nim-1.9.3/nim/lib/system/fatal.nim"
	nimTraceRefDyn(&(*dest__vCkiftuDKH5sFZLsuJkJYw_5).Sup.Sup.Sup.up, env__mx0njgyfbnJm7NN9b3EB7xg_5);
}
