/* Generated by Nim Compiler v1.6.12 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ;
struct tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ {
NI Field0;
NI Field1;
};
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, stareq___OOZsrcZmpu54485348Zmpu54485348_93)(NI* x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_5032)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;

#line 549 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!(framePtr__system_4513 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_4513).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	(*s).prev = framePtr__system_4513;
#line 557 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = s;
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		callDepthLimitReached__system_5032();
	}
	LA8_: ;
}

#line 99 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = (*framePtr__system_4513).prev;}

#line 465 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/arithmetics.nim"
static N_INLINE(void, stareq___OOZsrcZmpu54485348Zmpu54485348_93)(NI* x, NI y) {	NI TM__YqBQIdfvZX5pt75kDBsDLg_5;	nimfr_("*=", "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/arithmetics.nim");{
#line 468 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/arithmetics.nim"
	nimln_(468, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/arithmetics.nim");
#line 468 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/arithmetics.nim"
	if (nimMulInt((*x), y, &TM__YqBQIdfvZX5pt75kDBsDLg_5)) { raiseOverflow(); goto BeforeRet_;};	(*x) = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_5);	}BeforeRet_: ;
	popFrame();}

#line 1138 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
N_LIB_PRIVATE N_NIMCALL(NI, roof___OOZsrcZmpu54485348Zmpu54485348_86)(NI x, NI y) {	NI result;	nimfr_("^", "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");{	result = (NI)0;
#line 1154 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
	nimln_(1154, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");	switch (y) {
	case ((NI) 0):
	{
#line 1155 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		nimln_(1155, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");		result = ((NI) 1);	}
	break;
	case ((NI) 1):
	{
#line 1156 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		nimln_(1156, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");		result = x;	}
	break;
	case ((NI) 2):
	{		NI TM__YqBQIdfvZX5pt75kDBsDLg_2;
#line 1157 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		nimln_(1157, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");
#line 1157 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		if (nimMulInt(x, x, &TM__YqBQIdfvZX5pt75kDBsDLg_2)) { raiseOverflow(); goto BeforeRet_;};		result = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_2);	}
	break;
	case ((NI) 3):
	{		NI TM__YqBQIdfvZX5pt75kDBsDLg_3;		NI TM__YqBQIdfvZX5pt75kDBsDLg_4;
#line 1158 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		nimln_(1158, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");
#line 1158 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"

#line 1158 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		if (nimMulInt(x, x, &TM__YqBQIdfvZX5pt75kDBsDLg_3)) { raiseOverflow(); goto BeforeRet_;};		if (nimMulInt((NI)(TM__YqBQIdfvZX5pt75kDBsDLg_3), x, &TM__YqBQIdfvZX5pt75kDBsDLg_4)) { raiseOverflow(); goto BeforeRet_;};		result = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_4);	}
	break;
	default:
	{		tyTuple__1v9bKyksXWMsm0vNwmZ4EuQ T6_;		NI x_2;		NI y_2;
#line 1160 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		nimln_(1160, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");		T6_.Field0 = x;		T6_.Field1 = y;		x_2 = T6_.Field0;		y_2 = T6_.Field1;
#line 1161 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
		nimln_(1161, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");		result = ((NI) 1);		{
#line 1162 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
			nimln_(1162, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");			while (1) {
#line 1163 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
				nimln_(1163, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");				{
#line 1163 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"

#line 1163 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"

#line 1163 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
					if (!!(((NI)(((NI) (y_2)) & ((NI) 1)) == ((NI) 0)))) goto LA11_;

#line 1164 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
					nimln_(1164, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");
#line 1164 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
					stareq___OOZsrcZmpu54485348Zmpu54485348_93((&result), x_2);
				}
				LA11_: ;

#line 1165 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
				nimln_(1165, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");
#line 1165 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
				if (((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1)))) < ((NI) 0) || ((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1)))) > ((NI) 2147483647)){ raiseRangeErrorI((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1))), ((NI) 0), ((NI) 2147483647)); goto BeforeRet_;}				y_2 = ((NI) ((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI) 1)))));
#line 1166 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
				nimln_(1166, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");				{
#line 1166 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
					if (!(((NI) (y_2)) == ((NI) 0))) goto LA15_;

#line 1167 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
					nimln_(1167, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");					goto LA7;
				}
				LA15_: ;

#line 1168 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
				nimln_(1168, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim");
#line 1168 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/pure/math.nim"
				stareq___OOZsrcZmpu54485348Zmpu54485348_93((&x_2), x_2);
			}
		} LA7: ;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();	return result;}
