/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NF tyArray__AACV5tsODZUz7q0xBh9bP3A[7];
typedef NU8 tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q;
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_172)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg, NI64 x__ei4a8HqkfxKmzlWy521zOg);
static N_INLINE(void, addInt__stdZprivateZdigitsutils_189)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg_2, NI x__ei4a8HqkfxKmzlWy521zOg_2);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__main_82)(tyArray__AACV5tsODZUz7q0xBh9bP3A x__cUABn9cPb61a0KiWgFod2bA, NimStringV2 prefix__RhSYxOA0dybPI69cr5cEwMA, NimStringV2 separator__FZW9bQ4dKL5fBzvuUizH9cVQ, NimStringV2 suffix__wRShUxv5KxwMySIuTq9cD4Q);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZassertions_32)(NimStringV2* dest__9bysEU1F6xjkB13t7jg7tFg, NimStringV2 src__Q0EcxC6eCjA9adTTWfOBbQQ);
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g);
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i__j5Wg6rSPK6jprzM9co5KfZA, NI64 a__U8TO0Zlwhw51KAyAvquExw, NI64 b__hut4c5oxPM3l5OQ8nIwqqg);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s__qL2AkrAohOvo9bZZC15G6TA, NI addlen__uGPPC8Yor9a9avOoki7IG3AQ);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted__main_124)(NimStringV2* s__d8B3TpF9a1plpybwEXyKm9ag, NF x__kt6yfm0b4lpCHeMHG9cT1rw);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_4 = { 1 | NIM_STRLIT_FLAG, "[" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_5 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_4};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_6 = { 2 | NIM_STRLIT_FLAG, ", " };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_7 = {2, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_6};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__n49a9aYp5BrbXv9a6OCpJYm0g_8 = { 1 | NIM_STRLIT_FLAG, "]" };
static const NimStringV2 TM__n49a9aYp5BrbXv9a6OCpJYm0g_9 = {1, (NimStrPayload*)&TM__n49a9aYp5BrbXv9a6OCpJYm0g_8};
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4298;

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 114 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
static N_INLINE(void, addInt__stdZprivateZdigitsutils_189)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg_2, NI x__ei4a8HqkfxKmzlWy521zOg_2) {	nimfr_("addInt", "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 115 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(115, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 115 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	addInt__stdZprivateZdigitsutils_172(result__eysCSqL57sYgaohCkVYRVg_2, ((NI64) (x__ei4a8HqkfxKmzlWy521zOg_2)));
	popFrame();}

#line 16 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_8)(NI x__KsYCTjO9co8rDpst8JJ2TVg_2) {	
#line 16 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
NimStringV2 result;	nimfr_("$", "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");	result.len = 0; result.p = NIM_NIL;
#line 18 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	nimln_(18, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");
#line 18 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	addInt__stdZprivateZdigitsutils_189((&result), x__KsYCTjO9co8rDpst8JJ2TVg_2);
	popFrame();	return result;}

#line 20 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_11)(NI64 x__KsYCTjO9co8rDpst8JJ2TVg) {	
#line 20 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
NimStringV2 result;	nimfr_("$", "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");	result.len = 0; result.p = NIM_NIL;
#line 22 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	nimln_(22, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");
#line 22 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	addInt__stdZprivateZdigitsutils_172((&result), x__KsYCTjO9co8rDpst8JJ2TVg);
	popFrame();	return result;}

#line 8 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {	void* T1_;
#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));}

#line 1965 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"

#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}

#line 94 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
static N_INLINE(void, appendString)(NimStringV2* dest__Ws6Yi19bfxrbjCy9a9brzRV7A, NimStringV2 src__369aqaoei6FUsRf9cDAsKQ2g) {{
#line 95 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
	{		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_2;		NI TM__n49a9aYp5BrbXv9a6OCpJYm0g_3;
#line 95 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		if (!(((NI)0) < src__369aqaoei6FUsRf9cDAsKQ2g.len)) goto LA3_;

#line 97 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"

#line 97 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		if (nimAddInt(src__369aqaoei6FUsRf9cDAsKQ2g.len, ((NI)1), &TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) { raiseOverflow(); goto BeforeRet_;		};		if (((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) < ((NI)0) || ((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2), ((NI)0), ((NI)2147483647)); goto BeforeRet_;		}
#line 97 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		copyMem__system_1752(((void*) ((&(*(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).p).data[(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len]))), ((void*) ((&(*src__369aqaoei6FUsRf9cDAsKQ2g.p).data[((NI)0)]))), ((NI) ((NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_2))));

#line 98 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
		if (nimAddInt((*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len, src__369aqaoei6FUsRf9cDAsKQ2g.len, &TM__n49a9aYp5BrbXv9a6OCpJYm0g_3)) { raiseOverflow(); goto BeforeRet_;		};		(*dest__Ws6Yi19bfxrbjCy9a9brzRV7A).len = (NI)(TM__n49a9aYp5BrbXv9a6OCpJYm0g_3);	}
	LA3_: ;
	}BeforeRet_: ;
}

#line 89 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, collectionToString__main_82)(tyArray__AACV5tsODZUz7q0xBh9bP3A x__cUABn9cPb61a0KiWgFod2bA, NimStringV2 prefix__RhSYxOA0dybPI69cr5cEwMA, NimStringV2 separator__FZW9bQ4dKL5fBzvuUizH9cVQ, NimStringV2 suffix__wRShUxv5KxwMySIuTq9cD4Q) {	
#line 89 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
NimStringV2 result;	
#line 91 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
NIM_BOOL firstElement;	nimfr_("collectionToString", "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");	result.len = 0; result.p = NIM_NIL;
#line 25 "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim"
	nimln_(25, "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim");
#line 25 "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim"
	eqcopy___stdZassertions_32((&result), prefix__RhSYxOA0dybPI69cr5cEwMA);

#line 91 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	nimln_(91, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");	firstElement = NIM_TRUE;	{		
#line 92 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
NF value;		
#line 38 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q i;		value = (NF)0;
#line 38 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
		nimln_(38, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");		i = ((tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q)0);		{
#line 39 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
			nimln_(39, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");			while (1) {
#line 92 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
				nimln_(92, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");
#line 92 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
				value = x__cUABn9cPb61a0KiWgFod2bA[(i)- 0];
#line 92 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
				{					if (!firstElement) goto LA6_;

#line 94 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
					nimln_(94, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");
#line 94 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
					firstElement = NIM_FALSE;				}
				goto LA4_;
				LA6_: ;
				{
#line 96 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
					nimln_(96, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");					prepareAdd((&result), separator__FZW9bQ4dKL5fBzvuUizH9cVQ.len + 0);appendString((&result), separator__FZW9bQ4dKL5fBzvuUizH9cVQ);				}
				LA4_: ;

#line 92 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
				nimln_(92, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");
#line 92 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
				addQuoted__main_124((&result), value);

#line 41 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
				nimln_(41, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");				{
#line 41 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
					if (!(((tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q)6) <= i)) goto LA11_;

#line 41 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
					goto LA2;
				}
				LA11_: ;

#line 42 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
				nimln_(42, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");				i += ((NI)1);			}
		} LA2: ;
	}

#line 106 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	nimln_(106, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");	prepareAdd((&result), suffix__wRShUxv5KxwMySIuTq9cD4Q.len + 0);appendString((&result), suffix__wRShUxv5KxwMySIuTq9cD4Q);	popFrame();	return result;}

#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	
#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4298);	return result;}

#line 136 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___main_77)(tyArray__AACV5tsODZUz7q0xBh9bP3A x__3gbgphmPr2YyFiVFGB9c3cA) {	
#line 136 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
NimStringV2 result;NIM_BOOL* nimErr_;	nimfr_("$", "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 136 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	nimln_(136, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");
#line 138 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	nimln_(138, "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim");
#line 138 "/home/vincent/nim-1.9.3/nim/lib/system/dollars.nim"
	result = collectionToString__main_82(x__3gbgphmPr2YyFiVFGB9c3cA, TM__n49a9aYp5BrbXv9a6OCpJYm0g_5, TM__n49a9aYp5BrbXv9a6OCpJYm0g_7, TM__n49a9aYp5BrbXv9a6OCpJYm0g_9);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();	return result;}
