/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(x, y)
#define nimln_(x, y)
typedef struct tySequence__Zj5xKXgsXnI4n4hPS6nACA tySequence__Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content;
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA {
  NI len; tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content* p;
};


#ifndef tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content_PP
#define tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content_PP
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content { NI cap; NF data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p__0cx5cq1qFO3npuKvGWeDng, NI align__wrlqoTEqpzotN4hiPs9ce8A);

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459)(tySequence__Zj5xKXgsXnI4n4hPS6nACA* dest__FzTjCriiXFk9aKbEN1CBzjQ) {
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	if ((*dest__FzTjCriiXFk9aKbEN1CBzjQ).p && !((*dest__FzTjCriiXFk9aKbEN1CBzjQ).p->cap & NIM_STRLIT_FLAG)) { alignedDealloc((*dest__FzTjCriiXFk9aKbEN1CBzjQ).p, NIM_ALIGNOF(NF));}}
