/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__PbS9a6gkxCuxWEnFq4lOU9aw[24];
typedef NIM_CHAR tyArray__38Z69amCaoywES5tRmClBSw[200];
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s__S65jkNxJ72wMzHX9bQ0it8w, NIM_CHAR c__q53woDK9bF1K5bAKmsVpSkA);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s__qL2AkrAohOvo9bZZC15G6TA, NI addlen__uGPPC8Yor9a9avOoki7IG3AQ);
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_169)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg, NU64 x__ei4a8HqkfxKmzlWy521zOg);
static N_INLINE(void, addIntImpl__stdZprivateZdigitsutils_55)(NimStringV2* result__Skeud8zxbTJB3OSWEG9cFyw, NU64 x__zqEcnWhfwZxeOfmwW9blDtg);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i__qyERKXYav6dUvCjr1Ll1Vg, NI n__JY89cybmZsK4EqibzwKjS2A);
static N_INLINE(void, addChars__stdZprivateZdigitsutils_98)(NimStringV2* result__VT5D0VEmo9bLfBwxHIWEoLA, tyArray__PbS9a6gkxCuxWEnFq4lOU9aw x__vj9brNmxDW23RKVwR9a70bZw, NI start__x9aoBGYaKtpC1Jntewm9aWvg, NI n__8YJgvL7aYjQ9bEKwfPxGzpA);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i__j5Wg6rSPK6jprzM9co5KfZA, NI64 a__U8TO0Zlwhw51KAyAvquExw, NI64 b__hut4c5oxPM3l5OQ8nIwqqg);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s__19atMbr42TbRkrQSPFxaPZg, NI newLen__zdmruIpEqwmFKxid9btfbJw);
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE NIM_CONST tyArray__38Z69amCaoywES5tRmClBSw digits100__stdZprivateZdigitsutils_2 = {48,
48,
48,
49,
48,
50,
48,
51,
48,
52,
48,
53,
48,
54,
48,
55,
48,
56,
48,
57,
49,
48,
49,
49,
49,
50,
49,
51,
49,
52,
49,
53,
49,
54,
49,
55,
49,
56,
49,
57,
50,
48,
50,
49,
50,
50,
50,
51,
50,
52,
50,
53,
50,
54,
50,
55,
50,
56,
50,
57,
51,
48,
51,
49,
51,
50,
51,
51,
51,
52,
51,
53,
51,
54,
51,
55,
51,
56,
51,
57,
52,
48,
52,
49,
52,
50,
52,
51,
52,
52,
52,
53,
52,
54,
52,
55,
52,
56,
52,
57,
53,
48,
53,
49,
53,
50,
53,
51,
53,
52,
53,
53,
53,
54,
53,
55,
53,
56,
53,
57,
54,
48,
54,
49,
54,
50,
54,
51,
54,
52,
54,
53,
54,
54,
54,
55,
54,
56,
54,
57,
55,
48,
55,
49,
55,
50,
55,
51,
55,
52,
55,
53,
55,
54,
55,
55,
55,
56,
55,
57,
56,
48,
56,
49,
56,
50,
56,
51,
56,
52,
56,
53,
56,
54,
56,
55,
56,
56,
56,
57,
57,
48,
57,
49,
57,
50,
57,
51,
57,
52,
57,
53,
57,
54,
57,
55,
57,
56,
57,
57}
;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4298;

#line 65 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
static N_INLINE(void, nimAddCharV1)(NimStringV2* s__S65jkNxJ72wMzHX9bQ0it8w, NIM_CHAR c__q53woDK9bF1K5bAKmsVpSkA) {	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_2;	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_3;{
#line 67 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"

#line 67 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
	prepareAdd(s__S65jkNxJ72wMzHX9bQ0it8w, ((NI)1));

#line 68 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"

#line 68 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
	(*(*s__S65jkNxJ72wMzHX9bQ0it8w).p).data[(*s__S65jkNxJ72wMzHX9bQ0it8w).len] = c__q53woDK9bF1K5bAKmsVpSkA;
#line 69 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"

#line 69 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
	if (nimAddInt((*s__S65jkNxJ72wMzHX9bQ0it8w).len, ((NI)1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_2)) { raiseOverflow(); goto BeforeRet_;	};
#line 69 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
	(*(*s__S65jkNxJ72wMzHX9bQ0it8w).p).data[(NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_2)] = 0;
#line 70 "/home/vincent/nim-1.9.3/nim/lib/system/strs_v2.nim"
	if (nimAddInt((*s__S65jkNxJ72wMzHX9bQ0it8w).len, ((NI)1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_3)) { raiseOverflow(); goto BeforeRet_;	};	(*s__S65jkNxJ72wMzHX9bQ0it8w).len = (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_3);	}BeforeRet_: ;
}

#line 8 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {	void* T1_;
#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));}

#line 1965 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"

#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 42 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
static N_INLINE(void, addChars__stdZprivateZdigitsutils_98)(NimStringV2* result__VT5D0VEmo9bLfBwxHIWEoLA, tyArray__PbS9a6gkxCuxWEnFq4lOU9aw x__vj9brNmxDW23RKVwR9a70bZw, NI start__x9aoBGYaKtpC1Jntewm9aWvg, NI n__8YJgvL7aYjQ9bEKwfPxGzpA) {	
#line 43 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
NI old;	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_9;	nimfr_("addChars", "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");{
#line 43 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(43, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	old = (*result__VT5D0VEmo9bLfBwxHIWEoLA).len;
#line 44 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(44, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 44 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	if (nimAddInt(old, n__8YJgvL7aYjQ9bEKwfPxGzpA, &TM__J7BLF9cgvwzEso7aEL9cCOKw_9)) { raiseOverflow(); goto BeforeRet_;	};	if (((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_9)) < ((NI)0) || ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_9)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_9), ((NI)0), ((NI)2147483647)); goto BeforeRet_;	}	setLengthStrV2((&(*result__VT5D0VEmo9bLfBwxHIWEoLA)), ((NI) ((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_9))));
#line 52 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(52, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");	if (old < 0 || old >= (*result__VT5D0VEmo9bLfBwxHIWEoLA).len){ raiseIndexError2(old,(*result__VT5D0VEmo9bLfBwxHIWEoLA).len-1); goto BeforeRet_;	}	if ((NU)(start__x9aoBGYaKtpC1Jntewm9aWvg) > (NU)(23)){ raiseIndexError2(start__x9aoBGYaKtpC1Jntewm9aWvg, 23); goto BeforeRet_;	}	if ((n__8YJgvL7aYjQ9bEKwfPxGzpA) < ((NI)0) || (n__8YJgvL7aYjQ9bEKwfPxGzpA) > ((NI)2147483647)){ raiseRangeErrorI(n__8YJgvL7aYjQ9bEKwfPxGzpA, ((NI)0), ((NI)2147483647)); goto BeforeRet_;	}
#line 52 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	copyMem__system_1752(((void*) ((&(*result__VT5D0VEmo9bLfBwxHIWEoLA).p->data[old]))), ((void*) ((&x__vj9brNmxDW23RKVwR9a70bZw[(start__x9aoBGYaKtpC1Jntewm9aWvg)- 0]))), ((NI) (n__8YJgvL7aYjQ9bEKwfPxGzpA)));
	}BeforeRet_: ;
	popFrame();}

#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	
#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4298);	return result;}

#line 57 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
static N_INLINE(void, addIntImpl__stdZprivateZdigitsutils_55)(NimStringV2* result__Skeud8zxbTJB3OSWEG9cFyw, NU64 x__zqEcnWhfwZxeOfmwW9blDtg) {	
#line 58 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
tyArray__PbS9a6gkxCuxWEnFq4lOU9aw tmp;	
#line 59 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
NU64 num;	
#line 60 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
NI next_1;	NI TM__J7BLF9cgvwzEso7aEL9cCOKw_10;NIM_BOOL* nimErr_;	nimfr_("addIntImpl", "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");{nimErr_ = nimErrorFlag();
#line 59 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(59, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");	num = x__zqEcnWhfwZxeOfmwW9blDtg;
#line 60 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(60, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");	next_1 = ((NI)23);	{
#line 63 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(63, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");		while (1) {			
#line 64 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
NU64 originNum;			
#line 66 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
NI16 index;			NI TM__J7BLF9cgvwzEso7aEL9cCOKw_4;			NI TM__J7BLF9cgvwzEso7aEL9cCOKw_5;			NI TM__J7BLF9cgvwzEso7aEL9cCOKw_6;
#line 63 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			if (!((NU64)(100ULL) <= (NU64)(num))) goto LA2			;

#line 64 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(64, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");			originNum = num;
#line 65 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(65, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 65 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 65 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			num = (NU64)((NU64)(num) / (NU64)(100ULL));
#line 66 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(66, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 66 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 66 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 66 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			if ((NU64)((NU64)((NU64)((NU64)(originNum) - (NU64)((NU64)((NU64)(num) * (NU64)(100ULL))))) << (NU64)(((NI)1))) > (NU64)(((NI16)32767))){ raiseRangeErrorNoArgs(); goto BeforeRet_;			}			index = ((NI16) ((NU64)((NU64)((NU64)((NU64)(originNum) - (NU64)((NU64)((NU64)(num) * (NU64)(100ULL))))) << (NU64)(((NI)1)))));
#line 67 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(67, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");			if ((NU)(next_1) > (NU)(23)){ raiseIndexError2(next_1, 23); goto BeforeRet_;			}
#line 67 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 67 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			if (nimAddInt(index, ((NI16)1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_4)) { raiseOverflow(); goto BeforeRet_;			};			if (TM__J7BLF9cgvwzEso7aEL9cCOKw_4 < -32768 || TM__J7BLF9cgvwzEso7aEL9cCOKw_4 > 32767){ raiseOverflow(); goto BeforeRet_;			}			if ((NU)((NI16)(TM__J7BLF9cgvwzEso7aEL9cCOKw_4)) > (NU)(199)){ raiseIndexError2((NI16)(TM__J7BLF9cgvwzEso7aEL9cCOKw_4), 199); goto BeforeRet_;			}			tmp[(next_1)- 0] = digits100__stdZprivateZdigitsutils_2[((NI16)(TM__J7BLF9cgvwzEso7aEL9cCOKw_4))- 0];
#line 68 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(68, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 68 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			if (nimSubInt(next_1, ((NI)1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_5)) { raiseOverflow(); goto BeforeRet_;			};			if ((NU)((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5)) > (NU)(23)){ raiseIndexError2((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5), 23); goto BeforeRet_;			}
#line 68 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			if ((NU)(index) > (NU)(199)){ raiseIndexError2(index, 199); goto BeforeRet_;			}			tmp[((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_5))- 0] = digits100__stdZprivateZdigitsutils_2[(index)- 0];
#line 69 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(69, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");			if (nimSubInt(next_1, ((NI)2), &TM__J7BLF9cgvwzEso7aEL9cCOKw_6)) { raiseOverflow(); goto BeforeRet_;			};			next_1 = (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_6);		} LA2: ;
	}

#line 72 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(72, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");	{
#line 72 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		if (!((NU64)(num) < (NU64)(10ULL))) goto LA5_;

#line 73 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(73, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");		if ((NU)(next_1) > (NU)(23)){ raiseIndexError2(next_1, 23); goto BeforeRet_;		}
#line 73 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 73 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 73 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		tmp[(next_1)- 0] = ((NIM_CHAR) (((NI) ((NU8)((NU8)(((NU8)48)) + (NU8)(((NU8) (num))))))));	}
	goto LA3_;
	LA5_: ;
	{		
#line 75 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
NU64 index_2;		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_7;		NI TM__J7BLF9cgvwzEso7aEL9cCOKw_8;
#line 75 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(75, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 75 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		index_2 = (NU64)((NU64)(num) * (NU64)(2ULL));
#line 76 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(76, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");		if ((NU)(next_1) > (NU)(23)){ raiseIndexError2(next_1, 23); goto BeforeRet_;		}
#line 76 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 76 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		if ((NU)((NU64)((NU64)(index_2) + (NU64)(1ULL))) > (NU)(199)){ raiseIndexError2((NU64)((NU64)(index_2) + (NU64)(1ULL)), 199); goto BeforeRet_;		}		tmp[(next_1)- 0] = digits100__stdZprivateZdigitsutils_2[((NU64)((NU64)(index_2) + (NU64)(1ULL)))- 0];
#line 77 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(77, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 77 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		if (nimSubInt(next_1, ((NI)1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) { raiseOverflow(); goto BeforeRet_;		};		if ((NU)((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7)) > (NU)(23)){ raiseIndexError2((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7), 23); goto BeforeRet_;		}
#line 77 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		if ((NU)(index_2) > (NU)(199)){ raiseIndexError2(index_2, 199); goto BeforeRet_;		}		tmp[((NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_7))- 0] = digits100__stdZprivateZdigitsutils_2[(index_2)- 0];
#line 78 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(78, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");		if (nimSubInt(next_1, ((NI)1), &TM__J7BLF9cgvwzEso7aEL9cCOKw_8)) { raiseOverflow(); goto BeforeRet_;		};		next_1 = (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_8);	}
	LA3_: ;

#line 79 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(79, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 79 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	if (nimSubInt(((NI)24), next_1, &TM__J7BLF9cgvwzEso7aEL9cCOKw_10)) { raiseOverflow(); goto BeforeRet_;	};
#line 79 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	addChars__stdZprivateZdigitsutils_98(result__Skeud8zxbTJB3OSWEG9cFyw, tmp, next_1, (NI)(TM__J7BLF9cgvwzEso7aEL9cCOKw_10));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 84 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_169)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg, NU64 x__ei4a8HqkfxKmzlWy521zOg) {NIM_BOOL* nimErr_;	nimfr_("addInt", "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");{nimErr_ = nimErrorFlag();
#line 87 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(87, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 87 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	addIntImpl__stdZprivateZdigitsutils_55(result__eysCSqL57sYgaohCkVYRVg, x__ei4a8HqkfxKmzlWy521zOg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 91 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
N_LIB_PRIVATE N_NIMCALL(void, addInt__stdZprivateZdigitsutils_172)(NimStringV2* result__eysCSqL57sYgaohCkVYRVg, NI64 x__ei4a8HqkfxKmzlWy521zOg) {	
#line 98 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
NU64 numX60gensym3_;	nimfr_("addInt", "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");{	numX60gensym3_ = (NU64)0;
#line 99 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(99, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");	{
#line 99 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		if (!(x__ei4a8HqkfxKmzlWy521zOg < IL64(0))) goto LA3_;

#line 100 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(100, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");		{
#line 100 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			if (!(x__ei4a8HqkfxKmzlWy521zOg == (IL64(-9223372036854775807) - IL64(1)))) goto LA7_;

#line 101 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(101, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 101 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			numX60gensym3_ = ((NU64) (x__ei4a8HqkfxKmzlWy521zOg));		}
		goto LA5_;
		LA7_: ;
		{
#line 103 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			nimln_(103, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 103 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"

#line 103 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
			if (x__ei4a8HqkfxKmzlWy521zOg == (IL64(-9223372036854775807) - IL64(1))){ raiseOverflow(); goto BeforeRet_;			}			numX60gensym3_ = ((NU64) (-(x__ei4a8HqkfxKmzlWy521zOg)));		}
		LA5_: ;

#line 104 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(104, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");		nimAddCharV1((&(*result__eysCSqL57sYgaohCkVYRVg)), 45);	}
	goto LA1_;
	LA3_: ;
	{
#line 106 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		nimln_(106, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 106 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
		numX60gensym3_ = ((NU64) (x__ei4a8HqkfxKmzlWy521zOg));	}
	LA1_: ;

#line 112 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	nimln_(112, "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim");
#line 112 "/home/vincent/nim-1.9.3/nim/lib/std/private/digitsutils.nim"
	addInt__stdZprivateZdigitsutils_169(result__eysCSqL57sYgaohCkVYRVg, numX60gensym3_);
	}BeforeRet_: ;
	popFrame();}
