/* Generated by Nim Compiler v1.6.12 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <stdio.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;
  typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NIM_CHAR tyArray__eVNFTutn6un5gcq48fQLdg[65];
N_LIB_PRIVATE N_NIMCALL(NI, writeFloatToBufferSprintf__systemZformatfloat_68)(NIM_CHAR* buf, NF value);
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__systemZformatfloat_60)(NIM_CHAR* buf, NCSTRING value);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_5032)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, addCstringN__systemZformatfloat_5)(NimStringV2* result, NCSTRING buf, NI buflen);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s, NI newLen);
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR TFrame* framePtr__system_4513;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4861;

#line 549 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s) {
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!(framePtr__system_4513 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = ((NI16) 0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 554 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		(*s).calldepth = (NI16)((*framePtr__system_4513).calldepth + ((NI16) 1));	}
	LA1_: ;

#line 556 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	(*s).prev = framePtr__system_4513;
#line 557 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = s;
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"

#line 558 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
		callDepthLimitReached__system_5032();
	}
	LA8_: ;
}

#line 99 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	framePtr__system_4513 = (*framePtr__system_4513).prev;}

#line 36 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(void, writeToBuffer__systemZformatfloat_60)(NIM_CHAR* buf, NCSTRING value) {	NI i;	nimfr_("writeToBuffer", "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 37 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(37, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");	i = ((NI) 0);	{
#line 38 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(38, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");		while (1) {
#line 38 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"

#line 38 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			if (!!(((NU8)(value[i]) == (NU8)(0)))) goto LA2;

#line 39 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			nimln_(39, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");			buf[(i)- 0] = value[i];
#line 40 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			nimln_(40, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");			i += ((NI) 1);		} LA2: ;
	}
	popFrame();}

#line 423 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4861);	return result;}

#line 42 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(NI, writeFloatToBufferSprintf__systemZformatfloat_68)(NIM_CHAR* buf, NF value) {	NI result;	NI n;	int T1_;	NIM_BOOL hasDot;NIM_BOOL* nimErr_;	nimfr_("writeFloatToBufferSprintf", "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");{nimErr_ = nimErrorFlag();	result = (NI)0;
#line 47 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(47, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 47 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"

#line 47 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	T1_ = (int)0;	T1_ = sprintf(((NCSTRING) (buf)), "%.16g", value);	n = ((NI) (T1_));
#line 48 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(48, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");	hasDot = NIM_FALSE;	{		NI i;		NI colontmp_;		NI res;		i = (NI)0;		colontmp_ = (NI)0;
#line 49 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(49, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 49 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		colontmp_ = (NI)(n - ((NI) 1));
#line 90 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators_1.nim"
		nimln_(90, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators_1.nim");		res = ((NI) 0);		{
#line 91 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators_1.nim"
			nimln_(91, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators_1.nim");			while (1) {
#line 91 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators_1.nim"
				if (!(res <= colontmp_)) goto LA4;

#line 49 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
				nimln_(49, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");				i = res;
#line 49 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
				{
#line 50 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
					nimln_(50, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");					if (!((NU8)(buf[(i)- 0]) == (NU8)(44))) goto LA7_;

#line 51 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
					nimln_(51, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");					buf[(i)- 0] = 46;
#line 52 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
					nimln_(52, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");					hasDot = NIM_TRUE;				}
				goto LA5_;
				LA7_: ;
				{
#line 53 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
					nimln_(53, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");					if (!(((NU8)(buf[(i)- 0])) >= ((NU8)(97)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(122)) || ((NU8)(buf[(i)- 0])) >= ((NU8)(65)) && ((NU8)(buf[(i)- 0])) <= ((NU8)(90)) || ((NU8)(buf[(i)- 0])) == ((NU8)(46)))) goto LA10_;

#line 54 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
					nimln_(54, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");					hasDot = NIM_TRUE;				}
				goto LA5_;
				LA10_: ;
				LA5_: ;

#line 93 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators_1.nim"
				nimln_(93, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/iterators_1.nim");				res += ((NI) 1);			} LA4: ;
		}
	}

#line 55 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(55, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");	{
#line 55 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		if (!!(hasDot)) goto LA14_;

#line 56 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(56, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");		buf[(n)- 0] = 46;
#line 57 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(57, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 57 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		buf[((NI)(n + ((NI) 1)))- 0] = 48;
#line 58 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(58, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 58 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		buf[((NI)(n + ((NI) 2)))- 0] = 0;
#line 59 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(59, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 59 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		result = (NI)(n + ((NI) 2));	}
	goto LA12_;
	LA14_: ;
	{
#line 61 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(61, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");		result = n;	}
	LA12_: ;

#line 65 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(65, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");	{
#line 65 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"

#line 65 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		if (!(((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(110)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(78)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(68)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(100)) || ((NU8)(buf[((NI)(n - ((NI) 1)))- 0])) == ((NU8)(41)))) goto LA19_;

#line 66 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(66, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 66 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		writeToBuffer__systemZformatfloat_60(buf, "nan");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 67 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(67, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");		result = ((NI) 3);	}
	goto LA17_;
	LA19_: ;
	{
#line 68 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(68, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 68 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		if (!((NU8)(buf[((NI)(n - ((NI) 1)))- 0]) == (NU8)(70))) goto LA22_;

#line 69 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
		nimln_(69, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");		{
#line 69 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			if (!((NU8)(buf[(((NI) 0))- 0]) == (NU8)(45))) goto LA26_;

#line 70 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			nimln_(70, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 70 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			writeToBuffer__systemZformatfloat_60(buf, "-inf");
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 71 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			nimln_(71, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");			result = ((NI) 4);		}
		goto LA24_;
		LA26_: ;
		{
#line 73 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			nimln_(73, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 73 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			writeToBuffer__systemZformatfloat_60(buf, "inf");
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 74 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
			nimln_(74, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");			result = ((NI) 3);		}
		LA24_: ;
	}
	goto LA17_;
	LA22_: ;
	LA17_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 12 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(void, addCstringN__systemZformatfloat_5)(NimStringV2* result, NCSTRING buf, NI buflen) {	NI oldLen;	NI newLen;	void* T1_;	nimfr_("addCstringN", "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 14 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(14, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 14 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	oldLen = (*result).len;
#line 15 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(15, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 15 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	newLen = (NI)(oldLen + buflen);
#line 16 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(16, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");	setLengthStrV2((&(*result)), ((NI) (newLen)));
#line 17 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(17, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 17 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	T1_ = (void*)0;	T1_ = memcpy(((void*) ((&(*result).p->data[oldLen]))), ((void*) (buf)), ((size_t) (buflen)));	popFrame();}

#line 90 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
N_LIB_PRIVATE N_NIMCALL(void, addFloatSprintf__systemZformatfloat_111)(NimStringV2* result, NF x) {	tyArray__eVNFTutn6un5gcq48fQLdg buffer;	NI n;NIM_BOOL* nimErr_;	nimfr_("addFloatSprintf", "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");{nimErr_ = nimErrorFlag();
#line 95 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(95, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 95 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	n = writeFloatToBufferSprintf__systemZformatfloat_68(buffer, x);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 96 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	nimln_(96, "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim");
#line 96 "/home/vincent/.choosenim/toolchains/nim-1.6.12/lib/system/formatfloat.nim"
	addCstringN__systemZformatfloat_5(result, ((NCSTRING) ((&buffer[(((NI) 0))- 0]))), n);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
