/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, stareq___OOZsrcZmpu54485348Zmpu54485348_85)(NI* x__Y2xD2qxQ9aIextAwo0dRNRA, NI y__DqjjI1X9c1hlF4x5Z9c9bdiKA);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i__j5Wg6rSPK6jprzM9co5KfZA, NI64 a__U8TO0Zlwhw51KAyAvquExw, NI64 b__hut4c5oxPM3l5OQ8nIwqqg);
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 307 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
static N_INLINE(void, stareq___OOZsrcZmpu54485348Zmpu54485348_85)(NI* x__Y2xD2qxQ9aIextAwo0dRNRA, NI y__DqjjI1X9c1hlF4x5Z9c9bdiKA) {	NI TM__YqBQIdfvZX5pt75kDBsDLg_5;	nimfr_("*=", "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");{
#line 310 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	nimln_(310, "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");
#line 310 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"

#line 310 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	if (nimMulInt((*x__Y2xD2qxQ9aIextAwo0dRNRA), y__DqjjI1X9c1hlF4x5Z9c9bdiKA, &TM__YqBQIdfvZX5pt75kDBsDLg_5)) { raiseOverflow(); goto BeforeRet_;	};	(*x__Y2xD2qxQ9aIextAwo0dRNRA) = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_5);	}BeforeRet_: ;
	popFrame();}

#line 1136 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
N_LIB_PRIVATE N_NIMCALL(NI, roof___OOZsrcZmpu54485348Zmpu54485348_78)(NI x__CwzBi0yVLAjaE30ER4b9a9aA, NI y__Cb83q56OByU02eP8VQsClg) {	
#line 1136 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
NI result;	nimfr_("^", "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");{	result = (NI)0;
#line 1152 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
	nimln_(1152, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");	switch (y__Cb83q56OByU02eP8VQsClg) {
	case ((NI)0):
	{
#line 1153 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		nimln_(1153, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1153 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		result = ((NI)1);	}
	break;
	case ((NI)1):
	{
#line 1154 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		nimln_(1154, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1154 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		result = x__CwzBi0yVLAjaE30ER4b9a9aA;	}
	break;
	case ((NI)2):
	{		NI TM__YqBQIdfvZX5pt75kDBsDLg_2;
#line 1155 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		nimln_(1155, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1155 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"

#line 1155 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		if (nimMulInt(x__CwzBi0yVLAjaE30ER4b9a9aA, x__CwzBi0yVLAjaE30ER4b9a9aA, &TM__YqBQIdfvZX5pt75kDBsDLg_2)) { raiseOverflow(); goto BeforeRet_;		};		result = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_2);	}
	break;
	case ((NI)3):
	{		NI TM__YqBQIdfvZX5pt75kDBsDLg_3;		NI TM__YqBQIdfvZX5pt75kDBsDLg_4;
#line 1156 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		nimln_(1156, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1156 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"

#line 1156 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"

#line 1156 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		if (nimMulInt(x__CwzBi0yVLAjaE30ER4b9a9aA, x__CwzBi0yVLAjaE30ER4b9a9aA, &TM__YqBQIdfvZX5pt75kDBsDLg_3)) { raiseOverflow(); goto BeforeRet_;		};		if (nimMulInt((NI)(TM__YqBQIdfvZX5pt75kDBsDLg_3), x__CwzBi0yVLAjaE30ER4b9a9aA, &TM__YqBQIdfvZX5pt75kDBsDLg_4)) { raiseOverflow(); goto BeforeRet_;		};		result = (NI)(TM__YqBQIdfvZX5pt75kDBsDLg_4);	}
	break;
	default:
	{		
#line 1158 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
NI x_2;		
#line 1158 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
NI y_2;
#line 1158 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		nimln_(1158, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");		x_2 = x__CwzBi0yVLAjaE30ER4b9a9aA;
#line 1158 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		y_2 = y__Cb83q56OByU02eP8VQsClg;
#line 1159 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		nimln_(1159, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1159 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
		result = ((NI)1);		{
#line 1160 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
			nimln_(1160, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");			while (1) {
#line 1161 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
				nimln_(1161, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");				{
#line 1161 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"

#line 1161 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"

#line 1161 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
					if (!!(((NI)(((NI) (y_2)) & ((NI)1)) == ((NI)0)))) goto LA10_;

#line 1162 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
					nimln_(1162, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1162 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
					stareq___OOZsrcZmpu54485348Zmpu54485348_85((&result), x_2);
				}
				LA10_: ;

#line 1163 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
				nimln_(1163, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1163 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"

#line 1163 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
				if (((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI)1)))) < ((NI)0) || ((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI)1)))) > ((NI)2147483647)){ raiseRangeErrorI((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI)1))), ((NI)0), ((NI)2147483647)); goto BeforeRet_;				}				y_2 = ((NI) ((NI)((NI32)(((NI) (y_2))) >> (NU32)(((NI)1)))));
#line 1164 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
				nimln_(1164, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");				{
#line 1164 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
					if (!(((NI) (y_2)) == ((NI)0))) goto LA14_;

#line 1165 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
					nimln_(1165, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");					goto LA6;
				}
				LA14_: ;

#line 1166 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
				nimln_(1166, "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim");
#line 1166 "/home/vincent/nim-1.9.3/nim/lib/pure/math.nim"
				stareq___OOZsrcZmpu54485348Zmpu54485348_85((&x_2), x_2);
			}
		} LA6: ;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();	return result;}
