/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <i2cdev.h>
#include "driver/i2c.h"
#include "esp_log.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
typedef struct tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w;
typedef struct tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw;
typedef struct tySequence__Zj5xKXgsXnI4n4hPS6nACA tySequence__Zj5xKXgsXnI4n4hPS6nACA;
typedef struct tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg;
typedef struct tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA;
typedef struct tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A;
typedef struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyTuple__N4J9cV4JZGem3ljqqj5rT0Q;
typedef struct tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ;
typedef struct tyTuple__D5XwJS4yba0pRdHRq4pVrw tyTuple__D5XwJS4yba0pRdHRq4pVrw;
typedef struct tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw;
typedef NI32 tyEnum_i2c_mode_t__sAu6gHP6papa3cANrwGcyQ;
typedef NI32 tyEnum_gpio_num_t__aEau6azTKd9bpnbBbGm9c9ccQ;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
typedef NU8 tyArray__WplyaaK9a7ali8qLAFsJdKg[14];
struct tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w {i2c_dev_t device;
i2c_dev_t* device_ptr;
NU8 rate;
tyArray__qtqsWM5aXmcpMIVmvq3kAA buffer;
tyArray__WplyaaK9a7ali8qLAFsJdKg sensors;
NI gyro_range;
NI accel_range;
};
typedef NI tyArray__OQPb4glXtXQGOV29cAX1uQg[4];
typedef NF tyArray__AACV5tsODZUz7q0xBh9bP3A[7];
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA {
  NI len; tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content* p;
};
struct TNimTypeV2 {void* destructor;
NI size;
NI16 align;
NI16 depth;
NU32* display;
void* traceImpl;
void* typeInfoV1;
NI flags;
};
struct RootObj {TNimTypeV2* m_type;};
struct tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw {  RootObj Sup;NI colonstate_;
tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu60501;
};
struct tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg {NI rc;
NI rootIdx;
};
struct tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A {NI len;
NI cap;
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;
};
struct tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ {NI len;
NI cap;
tyTuple__D5XwJS4yba0pRdHRq4pVrw* d;
};
struct tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA {tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A traceStack;
tyObject_CellSeq__Mfu9bXxzF69aFsvEYW3nQCdQ toFree;
NI freed;
NI touched;
NI edges;
NI rcSum;
NIM_BOOL keepThreshold;
};
struct tyTuple__N4J9cV4JZGem3ljqqj5rT0Q {
void** Field0;
TNimTypeV2* Field1;
};
typedef tyTuple__N4J9cV4JZGem3ljqqj5rT0Q tyUncheckedArray__72XmdLy0QAaMtx66AmNKfA[1];
typedef NI tyArray__YHNmFTCzT8Rd9atJk8mVWFg[7];
typedef NU8 tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q;
struct tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw {NI a;
NI b;
};
typedef struct {
N_NIMCALL_PTR(NF, ClP_0) (NI x__d38lMMtWnHz7QyG8duLQTg, void* ClE_0);
void* ClE_0;
} tyProc__1un7Zt9bB5WVQaIdXFZeiNQ;
typedef N_CLOSURE_PTR(NF, TM__3PBxULbgl3reJpkZX7ik9aA_13) (NI x__d38lMMtWnHz7QyG8duLQTg);
typedef N_CLOSURE_PTR(NF, TM__3PBxULbgl3reJpkZX7ik9aA_15) (NI x__d38lMMtWnHz7QyG8duLQTg_2, void* ClE_0);
typedef struct {
N_NIMCALL_PTR(NF, ClP_0) (NF x__d38lMMtWnHz7QyG8duLQTg_3, void* ClE_0);
void* ClE_0;
} tyProc__zZ29aJqVt6bUiE9aXkliPF9bA;
typedef N_CLOSURE_PTR(NF, TM__3PBxULbgl3reJpkZX7ik9aA_16) (NF x__d38lMMtWnHz7QyG8duLQTg_3);


#ifndef tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content_PP
#define tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content_PP
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content { NI cap; NF data[SEQ_DECL_SIZE];};
#endif

      

#ifndef tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content_PP
#define tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content_PP
struct tySequence__Zj5xKXgsXnI4n4hPS6nACA_Content { NI cap; NF data[SEQ_DECL_SIZE];};
#endif

      N_LIB_PRIVATE N_NIMCALL(void, identify__OOZsrcZmpu54485348Zmpu54485348_40)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__9cAFG6WcyomJcQkY6V0PQSQ);
N_LIB_PRIVATE N_NIMCALL(NI32, i2c_read_reg__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_26)(i2c_dev_t* dev__8MQDuknW9cpR89cakjiYAXPg, NU8 reg__3q4TFB6wI6DiuvQJkNGbLg, NU8* val__8zJA0WAegaH46ePq8FmDRw);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, writeByte__OOZsrcZmpu54485348Zmpu54485348_44)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__MZAxMeCsPOyC9aWt4uU2ArQ, NU8 reg__0zWK8V6k1uasis89aCKnoAQ, NU8 val__HwQIoKzWH9bLEXLQOsMzJ2Q);
N_LIB_PRIVATE N_NIMCALL(NI32, i2c_write_reg__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_69)(i2c_dev_t* dev__fxPb9aYKeWiTfGEyUpwvo4A, NU8 reg__h0yBmVABU0pWIYDYnFhj5g, NU8 val__7WD9cF17t69a31OP30wDRfiA);
N_LIB_PRIVATE N_NIMCALL(void, setAccelRange__OOZsrcZmpu54485348Zmpu54485348_151)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__iFV18VZ4XOg7TTiXc7UtPw, NU8 fsr__AEDeIsv6PRY9akVZMP9cWbBQ);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i__qyERKXYav6dUvCjr1Ll1Vg, NI n__JY89cybmZsK4EqibzwKjS2A);
N_LIB_PRIVATE N_NIMCALL(void, setBitfield__OOZsrcZmpu54485348Zmpu54485348_70)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__bY8tP19b4pNORK83MzS255g, NU8 reg__kdKg4NuHtXvJjNm8wzomsA, NU8 pos__26gucsIM70GIO4oJG7zCZQ, NU8 length__gBiSU6zMVpDcvtu3WFlA9cQ, NU8 val__Rcvd724j3E6rNfiiXhVwfA);
N_LIB_PRIVATE N_NIMCALL(NU8, readByte__OOZsrcZmpu54485348Zmpu54485348_49)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__zLSvRvCsg357apo39bzxSCg, NU8 reg__DIgzry9bEcd8IDu2B6XorQA);
N_LIB_PRIVATE N_NIMCALL(NI, roof___OOZsrcZmpu54485348Zmpu54485348_78)(NI x__CwzBi0yVLAjaE30ER4b9a9aA, NI y__Cb83q56OByU02eP8VQsClg);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, setGyroRange__OOZsrcZmpu54485348Zmpu54485348_132)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__VCHLLqXhdv8ymLvv0VFuEA, NU8 fsr__wSE7klwiEQfV9bDRCbjWlhg);
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size__LZn6dneMVUSD9cVJcoc7Slw, NI alignment__eu9b1Xf7SGvOM5v8REyXVWA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_889)(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* dest__YT1jOIoeI9ch8nDJEHgtkAA);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p__dJRKNN7Lwiejao9bBZyAiiw, TNimTypeV2* desc__VkzDY9cpkn7dPDxj5VeV7eA);
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ);
N_LIB_PRIVATE N_NOINLINE(void, rememberCycle__system_3315)(NIM_BOOL isDestroyAction__wlZkTmY2exyvD4PmYZgCHw, tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg* s__rifrsJGbWaDLWZRj0ktOnA, TNimTypeV2* desc__YB9c2fwKemzor6iGIpZW9bIw);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_788)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* dest__ySbBDCBz3xruwKDcT9cyzYw);
N_LIB_PRIVATE N_NIMCALL(void, nimRawDispose)(void* p__fgKDMBQtwelfRnNv9bB0I5Q, NI alignment__upwtGXrI1BTnjD4u6YvIRw);
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___OOZsrcZmpu54485348Zmpu54485348_898)(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* dest__2pBZVGdE9bq7DJPHVNYIHyQ, void* env__Ldn8QOk9br2OmTcfhhVsRAQ);
static N_INLINE(void, nimTraceRef)(void* q__iar9btGuECYKSL1lzgb9b4xg, TNimTypeV2* desc__exnqLHpxJ9cKHeDoXN8PZew, void* env__YD9bPkv6BBenNNa9cdmvY9c6A);
static N_INLINE(void, add__system_2812)(tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A* s__G58rBzp9arUs2Le3q9bajUHA, void** c__glbQoed0fMuhXSt1wQUc7w, TNimTypeV2* t__afUUWAFqIJFXIEkjClESEA);
N_LIB_PRIVATE N_NOCONV(void*, allocSharedImpl)(NI size__PQOom62dq59az26ZBA3l8Lg);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA);
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i__j5Wg6rSPK6jprzM9co5KfZA, NI64 a__U8TO0Zlwhw51KAyAvquExw, NI64 b__hut4c5oxPM3l5OQ8nIwqqg);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p__XTVwAD5Qcy8cCUaIcC80hw);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZmpu54485348Zmpu54485348_775)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w** dest__qm0CxQfKqack6DR5C9c7XpA, tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* src__MBYCCXV9bHKvWzGWGOXUJgw, NIM_BOOL cyclic__l9c9b3rc7azOj9bcI2r5yWaAQ);
static N_INLINE(void, nimIncRefCyclic)(void* p__TmnUn9bk9ccKbVh5uWx44eqw, NIM_BOOL cyclic__SCqzrB5drdwXJPVAxXoIfg);
N_LIB_PRIVATE N_NIMCALL(void, readSensorsBytes__OOZsrcZmpu54485348Zmpu54485348_183)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__TULubN32R081mbeHI9brplQ, tyArray__WplyaaK9a7ali8qLAFsJdKg Result);
N_LIB_PRIVATE N_NIMCALL(void, unpackReadingsArr__OOZsrcZmpu54485348Zmpu54485348_235)(NU8* rawReadingBuffer__IlLpvOIOrig7ECmeGyoMQQ, tyArray__AACV5tsODZUz7q0xBh9bP3A Result);
static N_INLINE(void, bigEndian16__pureZendians_69)(void* outp__PRocgIk9c09aqc9cl80TYySDg, void* inp__jvhT9bTKTwBqR8wBwWpfBJQ);
static N_INLINE(void, swapEndian16__pureZendians_37)(void* outp__9a9aDt9bsB1ydhidpDj2azXJg, void* inp__KwRvnEek9b1J83o2WWGnGyg);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZsrcZmpu54485348Zmpu54485348_513)(NF* a__56K7rtvuXQY72nob2f5img, tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw x__AfBJoWX7F0u3oLcP4PfJvQ, NF* b__QEgulA9cLknbwTPriLDwlvA, NI b__QEgulA9cLknbwTPriLDwlvALen_0);
static N_INLINE(tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw, dotdot___stdZstrbasics_48)(NI a__KjwZroJB1iMTsXN9b0MEieA, NI b__m9c8KJepQ6mBYDEvipBikTw);
static N_INLINE(tySequence__Zj5xKXgsXnI4n4hPS6nACA, map__OOZsrcZmpu54485348Zmpu54485348_331)(NI* s__XiQvRWkRogP0UWEpi5iccw, NI s__XiQvRWkRogP0UWEpi5iccwLen_0, tyProc__1un7Zt9bB5WVQaIdXFZeiNQ op__QC3dsVU0qi9b06r48KvSj8g);
N_LIB_PRIVATE N_NIMCALL(void, newSeq__OOZsrcZmpu54485348Zmpu54485348_342)(tySequence__Zj5xKXgsXnI4n4hPS6nACA* s__JHX6dGKfrwZrkhFUhd74qw, NI len__WT25bUt2bu59aVKae2o1xsg);
N_LIB_PRIVATE N_NIMCALL(NF, colonanonymous___OOZsrcZmpu54485348Zmpu54485348_323)(NI v__h2DtGMVlHnjb3S2nH4ljBQ);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459)(tySequence__Zj5xKXgsXnI4n4hPS6nACA* dest__FzTjCriiXFk9aKbEN1CBzjQ);
static N_INLINE(tySequence__Zj5xKXgsXnI4n4hPS6nACA, map__OOZsrcZmpu54485348Zmpu54485348_656)(NF* s__XiQvRWkRogP0UWEpi5iccw_2, NI s__XiQvRWkRogP0UWEpi5iccw_2Len_0, tyProc__zZ29aJqVt6bUiE9aXkliPF9bA op__QC3dsVU0qi9b06r48KvSj8g_2);
N_LIB_PRIVATE N_NIMCALL(tySequence__Zj5xKXgsXnI4n4hPS6nACA, X5BX5D___OOZsrcZmpu54485348Zmpu54485348_624)(tyArray__AACV5tsODZUz7q0xBh9bP3A a__fUU4SHzjzYsVd50msB7qlQ, tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw x__9aNqPmXJfBR0vsEiqi1wHWA);
N_LIB_PRIVATE N_CLOSURE(NF, colonanonymous___OOZsrcZmpu54485348Zmpu54485348_649)(NF x__rlTOoiFM3msngiQDQX6vzA, void* ClE_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NIM_BOOL, nimDivInt)(NI a__gyDG7MUNDcfV5PkV6CtWqA, NI b__nuMwZHyCKxTfucixlf3raA, NI* res__IbLd8xOHMdBPOPXZpQSzlA);
N_LIB_PRIVATE N_CLOSURE(NF, colonanonymous___OOZsrcZmpu54485348Zmpu54485348_744)(NF x__rlTOoiFM3msngiQDQX6vzA_2, void* ClE_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_923)(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw** dest__YT1jOIoeI9ch8nDJEHgtkAA_2);
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p__dABzUdgzrkaSDMDdaWLtRg);
N_LIB_PRIVATE N_NIMCALL(void, nimDestroyAndDispose)(void* p__9avvNwjq1NdQwdCBwEYwA9bw);
N_LIB_PRIVATE TNimTypeV2 NTIv2__SwAT9aaEgco9ctOqrnwRJmUw_;
N_LIB_PRIVATE TNimTypeV2 NTIv2__6NnSei1Aqal1UkYo9blHh2w_;
N_LIB_PRIVATE NIM_CONST tyArray__OQPb4glXtXQGOV29cAX1uQg ACCEL_RANGE__OOZsrcZmpu54485348Zmpu54485348_12 = {((NI)2),
((NI)4),
((NI)8),
((NI)16)}
;
N_LIB_PRIVATE NIM_CONST tyArray__OQPb4glXtXQGOV29cAX1uQg GYRO_RANGE__OOZsrcZmpu54485348Zmpu54485348_13 = {((NI)250),
((NI)500),
((NI)1000),
((NI)2000)}
;
extern NU8 MPU6050_RA_WHO_AM_I__OOZsrcZmpu54485348Zmpu5448534895consts_154;
extern NU8 MPU6050_ADDRESS_AD0_LOW__OOZsrcZmpu54485348Zmpu5448534895consts_14;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4298;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NU8 MPU6050_RA_PWR_MGMT1__OOZsrcZmpu54485348Zmpu5448534895consts_143;
extern NU8 MPU6050_CLOCK_PLL_XGYRO__OOZsrcZmpu54485348Zmpu5448534895consts_23;
extern NU8 MPU6050_RA_PWR_MGMT2__OOZsrcZmpu54485348Zmpu5448534895consts_144;
extern NU8 MPU6050_RA_SMPLRT_DIV__OOZsrcZmpu54485348Zmpu5448534895consts_150;
extern NU8 MPU6050_RA_CONFIG__OOZsrcZmpu54485348Zmpu5448534895consts_117;
extern NU8 MPU6050_RA_ACCEL_CONFIG__OOZsrcZmpu54485348Zmpu5448534895consts_109;
extern NU8 MPU6050_ACONFIG_AFS_SEL_BIT__OOZsrcZmpu54485348Zmpu5448534895consts_8;
extern NU8 MPU6050_ACONFIG_AFS_SEL_LENGTH__OOZsrcZmpu54485348Zmpu5448534895consts_9;
extern NU8 MPU6050_ACCEL_FS2__OOZsrcZmpu54485348Zmpu5448534895consts_3;
extern NU8 MPU6050_RA_GYRO_CONFIG__OOZsrcZmpu54485348Zmpu5448534895consts_127;
extern NU8 MPU6050_GCONFIG_FS_SEL_BIT__OOZsrcZmpu54485348Zmpu5448534895consts_57;
extern NU8 MPU6050_GCONFIG_FS_SEL_LENGTH__OOZsrcZmpu54485348Zmpu5448534895consts_58;
extern NU8 MPU6050_GYRO_FS250__OOZsrcZmpu54485348Zmpu5448534895consts_61;
static NIM_CONST NU32 TM__3PBxULbgl3reJpkZX7ik9aA_4[1] = {3654449664};
N_LIB_PRIVATE TNimTypeV2 NTIv2__6NnSei1Aqal1UkYo9blHh2w_ = {.destructor = (void*)NIM_NIL, .size = sizeof(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w), .align = (NI16) NIM_ALIGNOF(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w), .depth = 0, .display = TM__3PBxULbgl3reJpkZX7ik9aA_4, .traceImpl = (void*)NIM_NIL, .flags = 0};
static NIM_CONST NU32 TM__3PBxULbgl3reJpkZX7ik9aA_5[2] = {3701606400, 1307904};
N_LIB_PRIVATE TNimTypeV2 NTIv2__SwAT9aaEgco9ctOqrnwRJmUw_ = {.destructor = (void*)eqdestroy___OOZsrcZmpu54485348Zmpu54485348_889, .size = sizeof(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw), .align = (NI16) NIM_ALIGNOF(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw), .depth = 1, .display = TM__3PBxULbgl3reJpkZX7ik9aA_5, .traceImpl = (void*)eqtrace___OOZsrcZmpu54485348Zmpu54485348_898, .flags = 0};
extern NU8 MPU6050_RA_ACCEL_XOUT_H__OOZsrcZmpu54485348Zmpu5448534895consts_110;

#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	
#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4298);	return result;}

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 43 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, identify__OOZsrcZmpu54485348Zmpu54485348_40)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__9cAFG6WcyomJcQkY6V0PQSQ) {	
#line 44 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NU8 who;	
#line 45 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NI32 res;NIM_BOOL* nimErr_;	nimfr_("identify", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();	who = (NU8)0;
#line 45 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(45, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 45 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	res = i2c_read_reg__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_26((*mpu6050__9cAFG6WcyomJcQkY6V0PQSQ).device_ptr, MPU6050_RA_WHO_AM_I__OOZsrcZmpu54485348Zmpu5448534895consts_154, (&who));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 46 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(46, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	{
#line 46 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 46 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		if (!!((who == MPU6050_ADDRESS_AD0_LOW__OOZsrcZmpu54485348Zmpu5448534895consts_14))) goto LA3_;

#line 47 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimln_(47, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 47 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		ESP_LOGD("MPU6050", "Could not answer MPU6050 \'Who am I\' 0x%02x", MPU6050_RA_WHO_AM_I__OOZsrcZmpu54485348Zmpu5448534895consts_154);
	}
	LA3_: ;

#line 48 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(48, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	{
#line 48 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 48 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		if (!!((res == ((NI32)0)))) goto LA7_;

#line 49 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimln_(49, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 49 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		ESP_LOGD("MPU6050", "Could not read from register 0x%02x", res);
	}
	LA7_: ;
	}BeforeRet_: ;
	popFrame();}

#line 51 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, writeByte__OOZsrcZmpu54485348Zmpu54485348_44)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__MZAxMeCsPOyC9aWt4uU2ArQ, NU8 reg__0zWK8V6k1uasis89aCKnoAQ, NU8 val__HwQIoKzWH9bLEXLQOsMzJ2Q) {	
#line 53 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NI32 res;NIM_BOOL* nimErr_;	nimfr_("writeByte", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();
#line 52 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(52, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 52 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	(*mpu6050__MZAxMeCsPOyC9aWt4uU2ArQ).buffer[(((NI)0))- 0] = val__HwQIoKzWH9bLEXLQOsMzJ2Q;
#line 53 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(53, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 53 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	res = i2c_write_reg__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_69((*mpu6050__MZAxMeCsPOyC9aWt4uU2ArQ).device_ptr, reg__0zWK8V6k1uasis89aCKnoAQ, val__HwQIoKzWH9bLEXLQOsMzJ2Q);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 54 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(54, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	{
#line 54 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 54 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		if (!!((res == ((NI32)0)))) goto LA3_;

#line 55 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimln_(55, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 55 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		ESP_LOGD("MPU6050", "Could not write from register 0x%02x", res);
	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();}

#line 57 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(NU8, readByte__OOZsrcZmpu54485348Zmpu54485348_49)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__zLSvRvCsg357apo39bzxSCg, NU8 reg__DIgzry9bEcd8IDu2B6XorQA) {	
#line 57 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NU8 result;	
#line 58 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NI32 res;	i2c_dev_t* T1_;	nimfr_("readByte", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{	result = (NU8)0;
#line 58 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(58, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	T1_ = (i2c_dev_t*)0;	T1_ = (*mpu6050__zLSvRvCsg357apo39bzxSCg).device_ptr;
#line 58 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	res = i2c_dev_read_reg(T1_, reg__DIgzry9bEcd8IDu2B6XorQA, ((void*) ((*mpu6050__zLSvRvCsg357apo39bzxSCg).buffer)), ((size_t)1));
#line 63 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(63, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	{
#line 63 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 63 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		if (!!((res == ((NI32)0)))) goto LA4_;

#line 64 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimln_(64, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 64 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		ESP_LOGD("MPU6050", "Could not read from register 0x%02x", res);
	}
	LA4_: ;

#line 65 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(65, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 57 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(57, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 65 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(65, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	result = (*mpu6050__zLSvRvCsg357apo39bzxSCg).buffer[(((NI)0))- 0];	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 67 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, setBitfield__OOZsrcZmpu54485348Zmpu54485348_70)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__bY8tP19b4pNORK83MzS255g, NU8 reg__kdKg4NuHtXvJjNm8wzomsA, NU8 pos__26gucsIM70GIO4oJG7zCZQ, NU8 length__gBiSU6zMVpDcvtu3WFlA9cQ, NU8 val__Rcvd724j3E6rNfiiXhVwfA) {	
#line 69 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NU8 old;	
#line 70 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NU8 shift;	
#line 71 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NU8 mask;	NI T1_;	NI TM__3PBxULbgl3reJpkZX7ik9aA_2;	
#line 72 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NU8 new_val;NIM_BOOL* nimErr_;	nimfr_("setBitfield", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();
#line 69 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(69, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 69 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	old = readByte__OOZsrcZmpu54485348Zmpu54485348_49(mpu6050__bY8tP19b4pNORK83MzS255g, reg__kdKg4NuHtXvJjNm8wzomsA);	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 70 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(70, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 70 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 70 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	shift = (NU8)((NU8)((NU8)((NU8)(pos__26gucsIM70GIO4oJG7zCZQ) - (NU8)(length__gBiSU6zMVpDcvtu3WFlA9cQ))) + (NU8)(((NU8)1)));
#line 71 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(71, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 71 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 71 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 71 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 71 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	T1_ = (NI)0;	T1_ = roof___OOZsrcZmpu54485348Zmpu54485348_78(((NI)2), ((NI) (length__gBiSU6zMVpDcvtu3WFlA9cQ)));	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	if (nimSubInt(T1_, ((NI)1), &TM__3PBxULbgl3reJpkZX7ik9aA_2)) { raiseOverflow(); goto BeforeRet_;	};	mask = (NU8)((NU8)(((NU8) ((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_2)))) << (NU8)(shift));
#line 72 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(72, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 72 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 72 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 72 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 72 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	new_val = (NU8)((NU8)(old & (NU8)((NU8) ~(mask))) | (NU8)((NU8)(val__Rcvd724j3E6rNfiiXhVwfA) << (NU8)(shift)));
#line 73 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(73, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 73 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	writeByte__OOZsrcZmpu54485348Zmpu54485348_44(mpu6050__bY8tP19b4pNORK83MzS255g, reg__kdKg4NuHtXvJjNm8wzomsA, new_val);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 112 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, setAccelRange__OOZsrcZmpu54485348Zmpu54485348_151)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__iFV18VZ4XOg7TTiXc7UtPw, NU8 fsr__AEDeIsv6PRY9akVZMP9cWbBQ) {NIM_BOOL* nimErr_;	nimfr_("setAccelRange", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();
#line 113 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(113, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 113 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	if ((NU)(fsr__AEDeIsv6PRY9akVZMP9cWbBQ) > (NU)(3)){ raiseIndexError2(fsr__AEDeIsv6PRY9akVZMP9cWbBQ, 3); goto BeforeRet_;	}	(*mpu6050__iFV18VZ4XOg7TTiXc7UtPw).accel_range = ACCEL_RANGE__OOZsrcZmpu54485348Zmpu54485348_12[(fsr__AEDeIsv6PRY9akVZMP9cWbBQ)- 0];
#line 114 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(114, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 114 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	setBitfield__OOZsrcZmpu54485348Zmpu54485348_70(mpu6050__iFV18VZ4XOg7TTiXc7UtPw, MPU6050_RA_ACCEL_CONFIG__OOZsrcZmpu54485348Zmpu5448534895consts_109, MPU6050_ACONFIG_AFS_SEL_BIT__OOZsrcZmpu54485348Zmpu5448534895consts_8, MPU6050_ACONFIG_AFS_SEL_LENGTH__OOZsrcZmpu54485348Zmpu5448534895consts_9, fsr__AEDeIsv6PRY9akVZMP9cWbBQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 103 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, setGyroRange__OOZsrcZmpu54485348Zmpu54485348_132)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__VCHLLqXhdv8ymLvv0VFuEA, NU8 fsr__wSE7klwiEQfV9bDRCbjWlhg) {NIM_BOOL* nimErr_;	nimfr_("setGyroRange", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();
#line 104 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(104, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 104 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	if ((NU)(fsr__wSE7klwiEQfV9bDRCbjWlhg) > (NU)(3)){ raiseIndexError2(fsr__wSE7klwiEQfV9bDRCbjWlhg, 3); goto BeforeRet_;	}	(*mpu6050__VCHLLqXhdv8ymLvv0VFuEA).gyro_range = GYRO_RANGE__OOZsrcZmpu54485348Zmpu54485348_13[(fsr__wSE7klwiEQfV9bDRCbjWlhg)- 0];
#line 105 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(105, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 105 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	setBitfield__OOZsrcZmpu54485348Zmpu54485348_70(mpu6050__VCHLLqXhdv8ymLvv0VFuEA, MPU6050_RA_GYRO_CONFIG__OOZsrcZmpu54485348Zmpu5448534895consts_127, MPU6050_GCONFIG_FS_SEL_BIT__OOZsrcZmpu54485348Zmpu5448534895consts_57, MPU6050_GCONFIG_FS_SEL_LENGTH__OOZsrcZmpu54485348Zmpu5448534895consts_58, fsr__wSE7klwiEQfV9bDRCbjWlhg);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 202 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, initDevice__OOZsrcZmpu54485348Zmpu54485348_862)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__CbSAqYObCdYW6l7zhwrUpw) {NIM_BOOL* nimErr_;	nimfr_("initDevice", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();
#line 203 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(203, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 203 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	identify__OOZsrcZmpu54485348Zmpu54485348_40(mpu6050__CbSAqYObCdYW6l7zhwrUpw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 206 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(206, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 206 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	writeByte__OOZsrcZmpu54485348Zmpu54485348_44(mpu6050__CbSAqYObCdYW6l7zhwrUpw, MPU6050_RA_PWR_MGMT1__OOZsrcZmpu54485348Zmpu5448534895consts_143, MPU6050_CLOCK_PLL_XGYRO__OOZsrcZmpu54485348Zmpu5448534895consts_23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 209 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(209, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 209 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	writeByte__OOZsrcZmpu54485348Zmpu54485348_44(mpu6050__CbSAqYObCdYW6l7zhwrUpw, MPU6050_RA_PWR_MGMT2__OOZsrcZmpu54485348Zmpu5448534895consts_144, ((NU8)0));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 212 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(212, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 212 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	writeByte__OOZsrcZmpu54485348Zmpu54485348_44(mpu6050__CbSAqYObCdYW6l7zhwrUpw, MPU6050_RA_SMPLRT_DIV__OOZsrcZmpu54485348Zmpu5448534895consts_150, (*mpu6050__CbSAqYObCdYW6l7zhwrUpw).rate);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 215 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(215, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 215 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	writeByte__OOZsrcZmpu54485348Zmpu54485348_44(mpu6050__CbSAqYObCdYW6l7zhwrUpw, MPU6050_RA_CONFIG__OOZsrcZmpu54485348Zmpu5448534895consts_117, ((NU8)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 218 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(218, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 218 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	setAccelRange__OOZsrcZmpu54485348Zmpu54485348_151(mpu6050__CbSAqYObCdYW6l7zhwrUpw, MPU6050_ACCEL_FS2__OOZsrcZmpu54485348Zmpu5448534895consts_3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
#line 219 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(219, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 219 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	setGyroRange__OOZsrcZmpu54485348Zmpu54485348_132(mpu6050__CbSAqYObCdYW6l7zhwrUpw, MPU6050_GYRO_FS250__OOZsrcZmpu54485348Zmpu5448534895consts_61);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 19 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw) {	void* T1_;
#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a__tZiCJHYy5dYyAh9cxwrrVhQ, v__iM7JOvZxArJIvbhGyRZG6Q, ((size_t) (size__ntsFNLS0mpvnjQFrZT7DCw)));}

#line 30 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	nimSetMem__systemZmemory_7(p__BuPKoq7dppy2upaj3KUaxw, ((int)0), size__ttWVm79bajRU3tarcA7MkLw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 363 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
static N_INLINE(NI, minuspercent___system_790)(NI x__nhqJNug5PDvy9ah8vc6uJ5Q, NI y__LJLJ0MGnpTb2U2nvMvG6MQ) {	
#line 363 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
NI result;	nimfr_("-%", "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");	result = (NI)0;
#line 363 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	nimln_(363, "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");
#line 364 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	nimln_(364, "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");
#line 368 "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim"
	nimln_(368, "/home/vincent/nim-1.9.3/nim/lib/system/arithmetics.nim");	result = ((NI) ((NU)((NU32)(((NU) (x__nhqJNug5PDvy9ah8vc6uJ5Q))) - (NU32)(((NU) (y__LJLJ0MGnpTb2U2nvMvG6MQ))))));	popFrame();	return result;}

#line 501 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicStatic)(void* p__dJRKNN7Lwiejao9bBZyAiiw, TNimTypeV2* desc__VkzDY9cpkn7dPDxj5VeV7eA) {	
#line 501 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("nimDecRefIsLastCyclicStatic", "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 502 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(502, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	{		
#line 503 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg* cell;		NI T5_;
#line 502 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 502 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		if (!!((p__dJRKNN7Lwiejao9bBZyAiiw == NIM_NIL))) goto LA3_;

#line 503 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(503, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
		nimln_(43, "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___system_790(((NI) (ptrdiff_t) (p__dJRKNN7Lwiejao9bBZyAiiw)), ((NI)8));		cell = ((tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg*) (T5_));
#line 504 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(504, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");		{
#line 504 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 504 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;

#line 505 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			nimln_(505, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 505 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__3PBxULbgl3reJpkZX7ik9aA_3;
#line 508 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			nimln_(508, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");			if (nimSubInt((*cell).rc, ((NI)16), &TM__3PBxULbgl3reJpkZX7ik9aA_3)) { raiseOverflow(); goto BeforeRet_;			};			(*cell).rc = (NI)(TM__3PBxULbgl3reJpkZX7ik9aA_3);		}
		LA6_: ;

#line 510 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(510, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 510 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		rememberCycle__system_3315(result, cell, desc__VkzDY9cpkn7dPDxj5VeV7eA);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_788)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* dest__ySbBDCBz3xruwKDcT9cyzYw) {}

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_889)(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* dest__YT1jOIoeI9ch8nDJEHgtkAA) {
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	{		NIM_BOOL T3_;
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicStatic((*dest__YT1jOIoeI9ch8nDJEHgtkAA).mpu60501, (&NTIv2__6NnSei1Aqal1UkYo9blHh2w_));		if (!T3_) goto LA4_;

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_788((*dest__YT1jOIoeI9ch8nDJEHgtkAA).mpu60501);

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimRawDispose((*dest__YT1jOIoeI9ch8nDJEHgtkAA).mpu60501, ((NI)NIM_ALIGNOF(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w)));
	}
	LA4_: ;
}

#line 8 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimCopyMem)(void* dest__HMDJtGX4ficduS9cTUiey0w, void* source__xDZEU1SRcEBuZ8mtbKQBhQ, NI size__9b8g0WMA1h1RvMwHOMW7yFA) {	void* T1_;
#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 10 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memcpy(dest__HMDJtGX4ficduS9cTUiey0w, source__xDZEU1SRcEBuZ8mtbKQBhQ, ((size_t) (size__9b8g0WMA1h1RvMwHOMW7yFA)));}

#line 1965 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
static N_INLINE(void, copyMem__system_1752)(void* dest__fJYjxXM6yYjbZ9agQpPnNNA, void* source__Y6ZnHEKiVLswf16AMGuQUA, NI size__YLlwRG7Z9bTiXmiSwU9cUHeA) {
#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"

#line 1966 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
	nimCopyMem(dest__fJYjxXM6yYjbZ9agQpPnNNA, source__Y6ZnHEKiVLswf16AMGuQUA, size__YLlwRG7Z9bTiXmiSwU9cUHeA);
}

#line 19 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
static N_INLINE(void, add__system_2812)(tyObject_CellSeq__lyOyvI8FT47RCBzCAvvv8A* s__G58rBzp9arUs2Le3q9bajUHA, void** c__glbQoed0fMuhXSt1wQUc7w, TNimTypeV2* t__afUUWAFqIJFXIEkjClESEA) {	
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
void** colontmp_;	
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
TNimTypeV2* colontmp__2;	NI TM__3PBxULbgl3reJpkZX7ik9aA_9;	nimfr_("add", "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");{
#line 20 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	nimln_(20, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");	{		NI TM__3PBxULbgl3reJpkZX7ik9aA_6;		
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
tyTuple__N4J9cV4JZGem3ljqqj5rT0Q* d;		NI TM__3PBxULbgl3reJpkZX7ik9aA_7;		void* T5_;		NI TM__3PBxULbgl3reJpkZX7ik9aA_8;
#line 20 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (!((*s__G58rBzp9arUs2Le3q9bajUHA).cap <= (*s__G58rBzp9arUs2Le3q9bajUHA).len)) goto LA3_;

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(21, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s__G58rBzp9arUs2Le3q9bajUHA).cap, ((NI)3), &TM__3PBxULbgl3reJpkZX7ik9aA_6)) { raiseOverflow(); goto BeforeRet_;		};		(*s__G58rBzp9arUs2Le3q9bajUHA).cap = (NI)((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_6) / ((NI)2));
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(23, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s__G58rBzp9arUs2Le3q9bajUHA).cap, ((NI)8), &TM__3PBxULbgl3reJpkZX7ik9aA_7)) { raiseOverflow(); goto BeforeRet_;		};		if (((NU) ((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_7))) > (NU)(((NI)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;		}
#line 23 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		T5_ = (void*)0;		T5_ = allocSharedImpl(((NI) (((NU) ((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_7))))));		d = ((tyTuple__N4J9cV4JZGem3ljqqj5rT0Q*) (T5_));
#line 26 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(26, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 26 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		if (nimMulInt((*s__G58rBzp9arUs2Le3q9bajUHA).len, ((NI)8), &TM__3PBxULbgl3reJpkZX7ik9aA_8)) { raiseOverflow(); goto BeforeRet_;		};		if (((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_8)) < ((NI)0) || ((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_8)) > ((NI)2147483647)){ raiseRangeErrorI((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_8), ((NI)0), ((NI)2147483647)); goto BeforeRet_;		}
#line 26 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		copyMem__system_1752(((void*) (d)), ((void*) ((*s__G58rBzp9arUs2Le3q9bajUHA).d)), ((NI) ((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_8))));

#line 28 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(28, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 28 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		deallocShared(((void*) ((*s__G58rBzp9arUs2Le3q9bajUHA).d)));

#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		nimln_(31, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");
#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
		(*s__G58rBzp9arUs2Le3q9bajUHA).d = d;	}
	LA3_: ;

#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	nimln_(33, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");	colontmp_ = c__glbQoed0fMuhXSt1wQUc7w;
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	colontmp__2 = t__afUUWAFqIJFXIEkjClESEA;
#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"

#line 33 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	(*s__G58rBzp9arUs2Le3q9bajUHA).d[(*s__G58rBzp9arUs2Le3q9bajUHA).len].Field0 = colontmp_;	(*s__G58rBzp9arUs2Le3q9bajUHA).d[(*s__G58rBzp9arUs2Le3q9bajUHA).len].Field1 = colontmp__2;
#line 34 "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim"
	nimln_(34, "/home/vincent/nim-1.9.3/nim/lib/system/cellseqs_v2.nim");	if (nimAddInt((*s__G58rBzp9arUs2Le3q9bajUHA).len, ((NI)1), &TM__3PBxULbgl3reJpkZX7ik9aA_9)) { raiseOverflow(); goto BeforeRet_;	};	(*s__G58rBzp9arUs2Le3q9bajUHA).len = (NI)(TM__3PBxULbgl3reJpkZX7ik9aA_9);	}BeforeRet_: ;
	popFrame();}

#line 122 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
static N_INLINE(void, nimTraceRef)(void* q__iar9btGuECYKSL1lzgb9b4xg, TNimTypeV2* desc__exnqLHpxJ9cKHeDoXN8PZew, void* env__YD9bPkv6BBenNNa9cdmvY9c6A) {	
#line 123 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
void** p;	nimfr_("nimTraceRef", "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 123 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(123, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	p = ((void**) (q__iar9btGuECYKSL1lzgb9b4xg));
#line 124 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(124, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	{		
#line 128 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA* j;
#line 124 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 124 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		if (!!(((*p) == NIM_NIL))) goto LA3_;

#line 128 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(128, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");		j = ((tyObject_GcEnv__w6PRWu9cTI0DLu7wssKaG9cA*) (env__YD9bPkv6BBenNNa9cdmvY9c6A));
#line 129 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(129, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 129 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		add__system_2812((&(*j).traceStack), p, desc__exnqLHpxJ9cKHeDoXN8PZew);
	}
	LA3_: ;
	popFrame();}

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqtrace___OOZsrcZmpu54485348Zmpu54485348_898)(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* dest__2pBZVGdE9bq7DJPHVNYIHyQ, void* env__Ldn8QOk9br2OmTcfhhVsRAQ) {
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimTraceRef(&(*dest__2pBZVGdE9bq7DJPHVNYIHyQ).mpu60501, (&NTIv2__6NnSei1Aqal1UkYo9blHh2w_), env__Ldn8QOk9br2OmTcfhhVsRAQ);
}

#line 44 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
static N_INLINE(void, nimIncRefCyclic)(void* p__TmnUn9bk9ccKbVh5uWx44eqw, NIM_BOOL cyclic__SCqzrB5drdwXJPVAxXoIfg) {	
#line 45 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg* h;	NI T1_;	NI TM__3PBxULbgl3reJpkZX7ik9aA_10;	nimfr_("nimIncRefCyclic", "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");{
#line 45 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(45, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
	nimln_(43, "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
	T1_ = (NI)0;	T1_ = minuspercent___system_790(((NI) (ptrdiff_t) (p__TmnUn9bk9ccKbVh5uWx44eqw)), ((NI)8));	h = ((tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg*) (T1_));
#line 46 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(46, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	if (nimAddInt((*h).rc, ((NI)16), &TM__3PBxULbgl3reJpkZX7ik9aA_10)) { raiseOverflow(); goto BeforeRet_;	};	(*h).rc = (NI)(TM__3PBxULbgl3reJpkZX7ik9aA_10);	}BeforeRet_: ;
	popFrame();}

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZmpu54485348Zmpu54485348_775)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w** dest__qm0CxQfKqack6DR5C9c7XpA, tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* src__MBYCCXV9bHKvWzGWGOXUJgw, NIM_BOOL cyclic__l9c9b3rc7azOj9bcI2r5yWaAQ) {	
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* colontmp_;
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	colontmp_ = (*dest__qm0CxQfKqack6DR5C9c7XpA);
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	{		if (!src__MBYCCXV9bHKvWzGWGOXUJgw) goto LA3_;

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimIncRefCyclic(src__MBYCCXV9bHKvWzGWGOXUJgw, cyclic__l9c9b3rc7azOj9bcI2r5yWaAQ);
	}
	LA3_: ;

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	(*dest__qm0CxQfKqack6DR5C9c7XpA) = src__MBYCCXV9bHKvWzGWGOXUJgw;
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	{		NIM_BOOL T7_;
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		T7_ = (NIM_BOOL)0;		T7_ = nimDecRefIsLastCyclicStatic(colontmp_, (&NTIv2__6NnSei1Aqal1UkYo9blHh2w_));		if (!T7_) goto LA8_;

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_788(colontmp_);

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimRawDispose(colontmp_, ((NI)NIM_ALIGNOF(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w)));
	}
	LA8_: ;
}

#line 131 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, readSensorsBytes__OOZsrcZmpu54485348Zmpu54485348_183)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__TULubN32R081mbeHI9brplQ, tyArray__WplyaaK9a7ali8qLAFsJdKg Result) {	
#line 132 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NI32 res;	i2c_dev_t* T1_;	nimfr_("readSensorsBytes", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{
#line 132 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(132, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	T1_ = (i2c_dev_t*)0;	T1_ = (*mpu6050__TULubN32R081mbeHI9brplQ).device_ptr;
#line 132 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	res = i2c_dev_read_reg(T1_, MPU6050_RA_ACCEL_XOUT_H__OOZsrcZmpu54485348Zmpu5448534895consts_110, ((void*) ((*mpu6050__TULubN32R081mbeHI9brplQ).sensors)), ((size_t)14));
#line 137 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(137, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	{
#line 137 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 137 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		if (!!((res == ((NI32)0)))) goto LA4_;

#line 138 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimln_(138, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 138 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		ESP_LOGD("MPU6050", "Could not read from register 0x%02x", res);
	}
	LA4_: ;

#line 139 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(139, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 131 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(131, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 139 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(139, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	nimCopyMem((void*)Result, (NIM_CONST void*)(*mpu6050__TULubN32R081mbeHI9brplQ).sensors, sizeof(tyArray__WplyaaK9a7ali8qLAFsJdKg));	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();}

#line 85 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
static N_INLINE(void, swapEndian16__pureZendians_37)(void* outp__9a9aDt9bsB1ydhidpDj2azXJg, void* inp__KwRvnEek9b1J83o2WWGnGyg) {	
#line 58 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
NU16 tmpX60gensym2_;	nimfr_("swapEndian16", "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim");	tmpX60gensym2_ = (NU16)0;
#line 59 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	nimln_(59, "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim");
#line 59 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	copyMem__system_1752(((void*) ((&tmpX60gensym2_))), inp__KwRvnEek9b1J83o2WWGnGyg, ((NI)2));

#line 60 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	nimln_(60, "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim");
#line 60 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"

#line 60 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	tmpX60gensym2_ = __builtin_bswap16(tmpX60gensym2_);
#line 94 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	nimln_(94, "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim");
#line 94 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	copyMem__system_1752(outp__9a9aDt9bsB1ydhidpDj2azXJg, ((void*) ((&tmpX60gensym2_))), ((NI)2));
	popFrame();}

#line 146 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
static N_INLINE(void, bigEndian16__pureZendians_69)(void* outp__PRocgIk9c09aqc9cl80TYySDg, void* inp__jvhT9bTKTwBqR8wBwWpfBJQ) {NIM_BOOL* nimErr_;	nimfr_("bigEndian16", "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim");{nimErr_ = nimErrorFlag();
#line 146 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	nimln_(146, "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim");
#line 146 "/home/vincent/nim-1.9.3/nim/lib/pure/endians.nim"
	swapEndian16__pureZendians_37(outp__PRocgIk9c09aqc9cl80TYySDg, inp__jvhT9bTKTwBqR8wBwWpfBJQ);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 368 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
static N_INLINE(tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw, dotdot___stdZstrbasics_48)(NI a__KjwZroJB1iMTsXN9b0MEieA, NI b__m9c8KJepQ6mBYDEvipBikTw) {	
#line 368 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw result;	nimfr_("..", "/home/vincent/nim-1.9.3/nim/lib/system.nim");	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw));
#line 378 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
	nimln_(378, "/home/vincent/nim-1.9.3/nim/lib/system.nim");
#line 378 "/home/vincent/nim-1.9.3/nim/lib/system.nim"
	nimZeroMem((void*)(&result), sizeof(tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw));	result.a = a__KjwZroJB1iMTsXN9b0MEieA;	result.b = b__m9c8KJepQ6mBYDEvipBikTw;	popFrame();	return result;}

#line 366 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
static N_INLINE(tySequence__Zj5xKXgsXnI4n4hPS6nACA, map__OOZsrcZmpu54485348Zmpu54485348_331)(NI* s__XiQvRWkRogP0UWEpi5iccw, NI s__XiQvRWkRogP0UWEpi5iccwLen_0, tyProc__1un7Zt9bB5WVQaIdXFZeiNQ op__QC3dsVU0qi9b06r48KvSj8g) {	
#line 366 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
tySequence__Zj5xKXgsXnI4n4hPS6nACA result;NIM_BOOL* nimErr_;	nimfr_("map", "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	nimln_(388, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	if ((s__XiQvRWkRogP0UWEpi5iccwLen_0) < ((NI)0) || (s__XiQvRWkRogP0UWEpi5iccwLen_0) > ((NI)2147483647)){ raiseRangeErrorI(s__XiQvRWkRogP0UWEpi5iccwLen_0, ((NI)0), ((NI)2147483647)); goto BeforeRet_;	}
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	newSeq__OOZsrcZmpu54485348Zmpu54485348_342((&result), ((NI) (s__XiQvRWkRogP0UWEpi5iccwLen_0)));
	{		
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
NI i;		
#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
NI colontmp_;		
#line 119 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
NI i_2;		i = (NI)0;		colontmp_ = (NI)0;
#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
		nimln_(117, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		nimln_(389, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		colontmp_ = s__XiQvRWkRogP0UWEpi5iccwLen_0;
#line 119 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
		nimln_(119, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");		i_2 = ((NI)0);		{
#line 120 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
			nimln_(120, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");			while (1) {				NF T4_;				NI TM__3PBxULbgl3reJpkZX7ik9aA_14;
#line 120 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
				if (!(i_2 < colontmp_)) goto LA3				;

#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				nimln_(389, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				i = i_2;
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				if (i < 0 || i >= result.len){ raiseIndexError2(i,result.len-1); goto BeforeRet_;				}
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				if (i < 0 || i >= s__XiQvRWkRogP0UWEpi5iccwLen_0){ raiseIndexError2(i,s__XiQvRWkRogP0UWEpi5iccwLen_0-1); goto BeforeRet_;				}				T4_ = (NF)0;				T4_ = op__QC3dsVU0qi9b06r48KvSj8g.ClE_0? op__QC3dsVU0qi9b06r48KvSj8g.ClP_0(s__XiQvRWkRogP0UWEpi5iccw[i], op__QC3dsVU0qi9b06r48KvSj8g.ClE_0):((TM__3PBxULbgl3reJpkZX7ik9aA_13)(op__QC3dsVU0qi9b06r48KvSj8g.ClP_0))(s__XiQvRWkRogP0UWEpi5iccw[i]);				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;				result.p->data[i] = T4_;
#line 122 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
				nimln_(122, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__3PBxULbgl3reJpkZX7ik9aA_14)) { raiseOverflow(); goto BeforeRet_;				};				i_2 = (NI)(TM__3PBxULbgl3reJpkZX7ik9aA_14);			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();	return result;}

#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(NF, colonanonymous___OOZsrcZmpu54485348Zmpu54485348_323)(NI v__h2DtGMVlHnjb3S2nH4ljBQ) {	
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NF result;	nimfr_(":anonymous", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	result = (NF)0;
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(128, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	result = ((NF) (v__h2DtGMVlHnjb3S2nH4ljBQ));	popFrame();	return result;}

#line 121 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, unpackReadingsArr__OOZsrcZmpu54485348Zmpu54485348_235)(NU8* rawReadingBuffer__IlLpvOIOrig7ECmeGyoMQQ, tyArray__AACV5tsODZUz7q0xBh9bP3A Result) {	
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tySequence__Zj5xKXgsXnI4n4hPS6nACA colontmpD_;	
#line 123 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyArray__YHNmFTCzT8Rd9atJk8mVWFg readings_i;	
#line 124 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyArray__AACV5tsODZUz7q0xBh9bP3A readings_t;	tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw T9_;	tyProc__1un7Zt9bB5WVQaIdXFZeiNQ T10_;NIM_BOOL* nimErr_;	nimfr_("unpackReadingsArr", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)Result, sizeof(tyArray__AACV5tsODZUz7q0xBh9bP3A));	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	nimZeroMem((void*)readings_i, sizeof(tyArray__YHNmFTCzT8Rd9atJk8mVWFg));	nimZeroMem((void*)readings_t, sizeof(tyArray__AACV5tsODZUz7q0xBh9bP3A));	{		
#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q idx;		
#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NI _;		
#line 156 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q i;		idx = (tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q)0;		_ = (NI)0;
#line 156 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
		nimln_(156, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");		i = ((tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q)0);		{
#line 157 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
			nimln_(157, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");			while (1) {				NI TM__3PBxULbgl3reJpkZX7ik9aA_11;				NI TM__3PBxULbgl3reJpkZX7ik9aA_12;
#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
				nimln_(126, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
				idx = i;
#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
				_ = readings_i[(i)- 0];
#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 127 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
				nimln_(127, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 127 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
				if (nimMulInt(idx, ((NI)2), &TM__3PBxULbgl3reJpkZX7ik9aA_11)) { raiseOverflow(); goto LA1_;				};				if ((NU)((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_11)) > (NU)(13)){ raiseIndexError2((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_11), 13); goto LA1_;				}
#line 126 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
				nimln_(126, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");				bigEndian16__pureZendians_69(((void*) ((&readings_i[(idx)- 0]))), ((void*) ((&rawReadingBuffer__IlLpvOIOrig7ECmeGyoMQQ[((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_11))- 0]))));
				if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 159 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
				nimln_(159, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");				{
#line 159 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
					if (!(((tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q)6) <= i)) goto LA7_;

#line 159 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
					goto LA3;
				}
				LA7_: ;

#line 160 "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim"
				nimln_(160, "/home/vincent/nim-1.9.3/nim/lib/system/iterators.nim");				if (nimAddInt(i, ((NI)1), &TM__3PBxULbgl3reJpkZX7ik9aA_12)) { raiseOverflow(); goto LA1_;				};				if (TM__3PBxULbgl3reJpkZX7ik9aA_12 < 0 || TM__3PBxULbgl3reJpkZX7ik9aA_12 > 6){ raiseOverflow(); goto LA1_;				}				i = (tyEnum_Fields__6O3c89c36VQb9anD7G0XF66Q)(TM__3PBxULbgl3reJpkZX7ik9aA_12);			}
		} LA3: ;
	}

#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(128, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	T9_ = dotdot___stdZstrbasics_48(((NI)0), ((NI)6));
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimZeroMem((void*)(&T10_), sizeof(tyProc__1un7Zt9bB5WVQaIdXFZeiNQ));	T10_.ClP_0 = ((TM__3PBxULbgl3reJpkZX7ik9aA_15) (colonanonymous___OOZsrcZmpu54485348Zmpu54485348_323)); T10_.ClE_0 = NIM_NIL;
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	colontmpD_ = map__OOZsrcZmpu54485348Zmpu54485348_331(readings_i, 7, T10_);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 128 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	X5BX5Deq___OOZsrcZmpu54485348Zmpu54485348_513(readings_t, T9_, ((colontmpD_).p) ? (colontmpD_.p->data) : NIM_NIL, colontmpD_.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 129 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(129, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 121 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(121, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 129 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(129, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	nimCopyMem((void*)Result, (NIM_CONST void*)readings_t, sizeof(tyArray__AACV5tsODZUz7q0xBh9bP3A));
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	nimln_(388, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD_));
	goto BeforeRet_;
	{		LA1_:;	}
	{
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}

#line 366 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
static N_INLINE(tySequence__Zj5xKXgsXnI4n4hPS6nACA, map__OOZsrcZmpu54485348Zmpu54485348_656)(NF* s__XiQvRWkRogP0UWEpi5iccw_2, NI s__XiQvRWkRogP0UWEpi5iccw_2Len_0, tyProc__zZ29aJqVt6bUiE9aXkliPF9bA op__QC3dsVU0qi9b06r48KvSj8g_2) {	
#line 366 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
tySequence__Zj5xKXgsXnI4n4hPS6nACA result;NIM_BOOL* nimErr_;	nimfr_("map", "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");{nimErr_ = nimErrorFlag();	result.len = 0; result.p = NIM_NIL;
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	nimln_(388, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	if ((s__XiQvRWkRogP0UWEpi5iccw_2Len_0) < ((NI)0) || (s__XiQvRWkRogP0UWEpi5iccw_2Len_0) > ((NI)2147483647)){ raiseRangeErrorI(s__XiQvRWkRogP0UWEpi5iccw_2Len_0, ((NI)0), ((NI)2147483647)); goto BeforeRet_;	}
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	newSeq__OOZsrcZmpu54485348Zmpu54485348_342((&result), ((NI) (s__XiQvRWkRogP0UWEpi5iccw_2Len_0)));
	{		
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
NI i;		
#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
NI colontmp_;		
#line 119 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
NI i_2;		i = (NI)0;		colontmp_ = (NI)0;
#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
		nimln_(117, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		nimln_(389, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		colontmp_ = s__XiQvRWkRogP0UWEpi5iccw_2Len_0;
#line 119 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
		nimln_(119, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");		i_2 = ((NI)0);		{
#line 120 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
			nimln_(120, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");			while (1) {				NF T4_;				NI TM__3PBxULbgl3reJpkZX7ik9aA_17;
#line 120 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
				if (!(i_2 < colontmp_)) goto LA3				;

#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				nimln_(389, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				i = i_2;
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				if (i < 0 || i >= result.len){ raiseIndexError2(i,result.len-1); goto BeforeRet_;				}
#line 389 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
				if (i < 0 || i >= s__XiQvRWkRogP0UWEpi5iccw_2Len_0){ raiseIndexError2(i,s__XiQvRWkRogP0UWEpi5iccw_2Len_0-1); goto BeforeRet_;				}				T4_ = (NF)0;				T4_ = op__QC3dsVU0qi9b06r48KvSj8g_2.ClE_0? op__QC3dsVU0qi9b06r48KvSj8g_2.ClP_0(s__XiQvRWkRogP0UWEpi5iccw_2[i], op__QC3dsVU0qi9b06r48KvSj8g_2.ClE_0):((TM__3PBxULbgl3reJpkZX7ik9aA_16)(op__QC3dsVU0qi9b06r48KvSj8g_2.ClP_0))(s__XiQvRWkRogP0UWEpi5iccw_2[i]);				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;				result.p->data[i] = T4_;
#line 122 "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim"
				nimln_(122, "/home/vincent/nim-1.9.3/nim/lib/system/iterators_1.nim");				if (nimAddInt(i_2, ((NI)1), &TM__3PBxULbgl3reJpkZX7ik9aA_17)) { raiseOverflow(); goto BeforeRet_;				};				i_2 = (NI)(TM__3PBxULbgl3reJpkZX7ik9aA_17);			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();	return result;}

#line 122 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
static N_INLINE(NIM_BOOL, nimDivInt)(NI a__gyDG7MUNDcfV5PkV6CtWqA, NI b__nuMwZHyCKxTfucixlf3raA, NI* res__IbLd8xOHMdBPOPXZpQSzlA) {	
#line 122 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
NIM_BOOL result;	result = (NIM_BOOL)0;
#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
	{		NIM_BOOL T3_;
#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
		T3_ = (NIM_BOOL)0;
#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
		T3_ = (a__gyDG7MUNDcfV5PkV6CtWqA == ((NI)(-2147483647 -1)));		if (!(T3_)) goto LA4_;

#line 117 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
		T3_ = (b__nuMwZHyCKxTfucixlf3raA == ((NI)-1));		LA4_: ;
		if (!T3_) goto LA5_;

#line 118 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"

#line 118 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
		result = NIM_TRUE;	}
	goto LA1_;
	LA5_: ;
	{
#line 120 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"

#line 120 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"

#line 120 "/home/vincent/nim-1.9.3/nim/lib/system/integerops.nim"
		(*res__IbLd8xOHMdBPOPXZpQSzlA) = (NI)(a__gyDG7MUNDcfV5PkV6CtWqA / b__nuMwZHyCKxTfucixlf3raA);	}
	LA1_: ;
	return result;}

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_CLOSURE(NF, colonanonymous___OOZsrcZmpu54485348Zmpu54485348_649)(NF x__rlTOoiFM3msngiQDQX6vzA, void* ClE_0) {	
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NF result;	
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* colonenvP_;	NI TM__3PBxULbgl3reJpkZX7ik9aA_18;	nimfr_(":anonymous", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{	result = (NF)0;	colonenvP_ = (tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw*) ClE_0;
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(149, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	if ((*(*colonenvP_).mpu60501).accel_range == 0){ raiseDivByZero(); goto BeforeRet_;	}	if (nimDivInt(((NI)65536), (*(*colonenvP_).mpu60501).accel_range, &TM__3PBxULbgl3reJpkZX7ik9aA_18)) { raiseOverflow(); goto BeforeRet_;	};	result = ((NF)(x__rlTOoiFM3msngiQDQX6vzA) / (NF)(((NF) ((NI)((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_18) / ((NI)2))))));	}BeforeRet_: ;
	popFrame();	return result;}

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_CLOSURE(NF, colonanonymous___OOZsrcZmpu54485348Zmpu54485348_744)(NF x__rlTOoiFM3msngiQDQX6vzA_2, void* ClE_0) {	
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
NF result;	
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* colonenvP_;	NI TM__3PBxULbgl3reJpkZX7ik9aA_19;	nimfr_(":anonymous", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{	result = (NF)0;	colonenvP_ = (tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw*) ClE_0;
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(150, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	if ((*(*colonenvP_).mpu60501).gyro_range == 0){ raiseDivByZero(); goto BeforeRet_;	}	if (nimDivInt(((NI)65536), (*(*colonenvP_).mpu60501).gyro_range, &TM__3PBxULbgl3reJpkZX7ik9aA_19)) { raiseOverflow(); goto BeforeRet_;	};	result = ((NF)(x__rlTOoiFM3msngiQDQX6vzA_2) / (NF)(((NF) ((NI)((NI)(TM__3PBxULbgl3reJpkZX7ik9aA_19) / ((NI)2))))));	}BeforeRet_: ;
	popFrame();	return result;}

#line 477 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
static N_INLINE(NIM_BOOL, nimDecRefIsLastCyclicDyn)(void* p__dABzUdgzrkaSDMDdaWLtRg) {	
#line 477 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
NIM_BOOL result;NIM_BOOL* nimErr_;	nimfr_("nimDecRefIsLastCyclicDyn", "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");{nimErr_ = nimErrorFlag();	result = (NIM_BOOL)0;
#line 478 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
	nimln_(478, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");	{		
#line 479 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg* cell;		NI T5_;
#line 478 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 478 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		if (!!((p__dABzUdgzrkaSDMDdaWLtRg == NIM_NIL))) goto LA3_;

#line 479 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(479, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
		nimln_(43, "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim");
#line 43 "/home/vincent/nim-1.9.3/nim/lib/system/arc.nim"
		T5_ = (NI)0;		T5_ = minuspercent___system_790(((NI) (ptrdiff_t) (p__dABzUdgzrkaSDMDdaWLtRg)), ((NI)8));		cell = ((tyObject_RefHeader__8Yy6cdkFXU6cgot0XGjy9bg*) (T5_));
#line 480 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(480, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");		{
#line 480 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"

#line 480 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			if (!((NI)((*cell).rc & ((NI)-16)) == ((NI)0))) goto LA8_;

#line 481 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			nimln_(481, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 481 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			result = NIM_TRUE;		}
		goto LA6_;
		LA8_: ;
		{			NI TM__3PBxULbgl3reJpkZX7ik9aA_20;
#line 484 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
			nimln_(484, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");			if (nimSubInt((*cell).rc, ((NI)16), &TM__3PBxULbgl3reJpkZX7ik9aA_20)) { raiseOverflow(); goto BeforeRet_;			};			(*cell).rc = (NI)(TM__3PBxULbgl3reJpkZX7ik9aA_20);		}
		LA6_: ;

#line 486 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		nimln_(486, "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim");
#line 486 "/home/vincent/nim-1.9.3/nim/lib/system/orc.nim"
		rememberCycle__system_3315(result, cell, (*((TNimTypeV2**) (p__dABzUdgzrkaSDMDdaWLtRg))));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZmpu54485348Zmpu54485348_923)(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw** dest__YT1jOIoeI9ch8nDJEHgtkAA_2) {
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	{		NIM_BOOL T3_;
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		T3_ = (NIM_BOOL)0;		T3_ = nimDecRefIsLastCyclicDyn((*dest__YT1jOIoeI9ch8nDJEHgtkAA_2));		if (!T3_) goto LA4_;

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimDestroyAndDispose((*dest__YT1jOIoeI9ch8nDJEHgtkAA_2));
	}
	LA4_: ;
}

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
N_LIB_PRIVATE N_NIMCALL(void, readSensorsScaled__OOZsrcZmpu54485348Zmpu54485348_231)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__v4QYeTetDBAQ6n7UZ9c3tYg, tyArray__AACV5tsODZUz7q0xBh9bP3A Result) {	
#line 146 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* colonenv_;	
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tySequence__Zj5xKXgsXnI4n4hPS6nACA colontmpD_;	
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tySequence__Zj5xKXgsXnI4n4hPS6nACA colontmpD__2;	
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tySequence__Zj5xKXgsXnI4n4hPS6nACA colontmpD__3;	
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tySequence__Zj5xKXgsXnI4n4hPS6nACA colontmpD__4;	tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw* T2_;	tyArray__WplyaaK9a7ali8qLAFsJdKg T3_;	
#line 147 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
tyArray__AACV5tsODZUz7q0xBh9bP3A floatReadings;	tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw T4_;	tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw T5_;	tyProc__zZ29aJqVt6bUiE9aXkliPF9bA T6_;	tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw T7_;	tyObject_HSlice__3vj44mZQyy7uB5RTeHP2Vw T8_;	tyProc__zZ29aJqVt6bUiE9aXkliPF9bA T9_;NIM_BOOL* nimErr_;	nimfr_("readSensorsScaled", "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");{nimErr_ = nimErrorFlag();	nimZeroMem((void*)Result, sizeof(tyArray__AACV5tsODZUz7q0xBh9bP3A));	colonenv_ = NIM_NIL;	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;	colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;	colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;	colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
#line 146 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(146, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 146 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	T2_ = NIM_NIL;	T2_ = (tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw*) nimNewObj(sizeof(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw), NIM_ALIGNOF(tyObject_Env_mpu6050dotnim_readSensorsScaled___SwAT9aaEgco9ctOqrnwRJmUw));	(*T2_).Sup.m_type = (&NTIv2__SwAT9aaEgco9ctOqrnwRJmUw_);	colonenv_ = T2_;
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(145, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	eqcopy___OOZsrcZmpu54485348Zmpu54485348_775(&(*colonenv_).mpu60501, mpu6050__v4QYeTetDBAQ6n7UZ9c3tYg, NIM_TRUE);

#line 146 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(146, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 146 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 146 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimZeroMem((void*)T3_, sizeof(tyArray__WplyaaK9a7ali8qLAFsJdKg));	readSensorsBytes__OOZsrcZmpu54485348Zmpu54485348_183((*colonenv_).mpu60501, T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	(void)(T3_);
	nimZeroMem((void*)floatReadings, sizeof(tyArray__AACV5tsODZUz7q0xBh9bP3A));
#line 147 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(147, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 147 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	unpackReadingsArr__OOZsrcZmpu54485348Zmpu54485348_235((*(*colonenv_).mpu60501).sensors, floatReadings);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(149, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	T4_ = dotdot___stdZstrbasics_48(((NI)0), ((NI)2));
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	T5_ = dotdot___stdZstrbasics_48(((NI)0), ((NI)2));
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	colontmpD_ = X5BX5D___OOZsrcZmpu54485348Zmpu54485348_624(floatReadings, T5_);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	nimZeroMem((void*)(&T6_), sizeof(tyProc__zZ29aJqVt6bUiE9aXkliPF9bA));	T6_.ClP_0 = colonanonymous___OOZsrcZmpu54485348Zmpu54485348_649; T6_.ClE_0 = colonenv_;
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	colontmpD__2 = map__OOZsrcZmpu54485348Zmpu54485348_656(((colontmpD_).p) ? (colontmpD_.p->data) : NIM_NIL, colontmpD_.len, T6_);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 149 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	X5BX5Deq___OOZsrcZmpu54485348Zmpu54485348_513(floatReadings, T4_, ((colontmpD__2).p) ? (colontmpD__2.p->data) : NIM_NIL, colontmpD__2.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(150, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	T7_ = dotdot___stdZstrbasics_48(((NI)4), ((NI)6));
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"

#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	T8_ = dotdot___stdZstrbasics_48(((NI)0), ((NI)2));
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	colontmpD__3 = X5BX5D___OOZsrcZmpu54485348Zmpu54485348_624(floatReadings, T8_);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;	nimZeroMem((void*)(&T9_), sizeof(tyProc__zZ29aJqVt6bUiE9aXkliPF9bA));	T9_.ClP_0 = colonanonymous___OOZsrcZmpu54485348Zmpu54485348_744; T9_.ClE_0 = colonenv_;
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	colontmpD__4 = map__OOZsrcZmpu54485348Zmpu54485348_656(((colontmpD__3).p) ? (colontmpD__3.p->data) : NIM_NIL, colontmpD__3.len, T9_);	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 150 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	X5BX5Deq___OOZsrcZmpu54485348Zmpu54485348_513(floatReadings, T7_, ((colontmpD__4).p) ? (colontmpD__4.p->data) : NIM_NIL, colontmpD__4.len);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
#line 152 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(152, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(145, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 152 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(152, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");	nimCopyMem((void*)Result, (NIM_CONST void*)floatReadings, sizeof(tyArray__AACV5tsODZUz7q0xBh9bP3A));
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	nimln_(388, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD__4));

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD__3));

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD__2));

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
	eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD_));

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	nimln_(145, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
	eqdestroy___OOZsrcZmpu54485348Zmpu54485348_923(&colonenv_);
	goto BeforeRet_;
	{		LA1_:;	}
	{
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		nimln_(388, "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim");
#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD__4));

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD__3));

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD__2));

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"

#line 388 "/home/vincent/nim-1.9.3/nim/lib/pure/collections/sequtils.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_459((&colontmpD_));

#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		nimln_(145, "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim");
#line 145 "/home/vincent/Documents/Nim/MCU/NIMPU6050/src/mpu6050/mpu6050.nim"
		eqdestroy___OOZsrcZmpu54485348Zmpu54485348_923(&colonenv_);
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
	popFrame();}
