/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <i2cdev.h>
#include <string.h>
#include "esp_log.h"
#include "driver/i2c.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
typedef NU8 tyArray__bN9bddWn8oiNSHn2MqEJSZQ[2];
typedef NI32 tyEnum_i2c_mode_t__sAu6gHP6papa3cANrwGcyQ;
typedef NI32 tyEnum_gpio_num_t__aEau6azTKd9bpnbBbGm9c9ccQ;
N_LIB_PRIVATE N_NIMCALL(void, i2cDeviceInit__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_25)(void);
N_LIB_PRIVATE N_NIMCALL(void, doCheck__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_91)(NI32 ret__2m9cRyGpkDK2tiYARF9amKrg);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw);
N_LIB_PRIVATE NIM_BOOL i2cStarted__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_24;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4298;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;

#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	
#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4298);	return result;}

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 34 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
N_LIB_PRIVATE N_NIMCALL(void, i2cDeviceInit__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_25)(void) {NIM_BOOL* nimErr_;	nimfr_("i2cDeviceInit", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");{nimErr_ = nimErrorFlag();
#line 35 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(35, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");	{		NI32 T5_;
#line 35 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		if (!!(i2cStarted__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_24)) goto LA3_;

#line 36 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(36, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 36 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 36 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		T5_ = (NI32)0;		T5_ = i2cdev_init();
#line 36 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		doCheck__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZgeneral_91(T5_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}
	LA3_: ;
	}BeforeRet_: ;
	popFrame();}

#line 19 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw) {	void* T1_;
#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a__tZiCJHYy5dYyAh9cxwrrVhQ, v__iM7JOvZxArJIvbhGyRZG6Q, ((size_t) (size__ntsFNLS0mpvnjQFrZT7DCw)));}

#line 30 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	nimSetMem__systemZmemory_7(p__BuPKoq7dppy2upaj3KUaxw, ((int)0), size__ttWVm79bajRU3tarcA7MkLw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 41 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
N_LIB_PRIVATE N_NIMCALL(NI32, i2c_read_reg__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_26)(i2c_dev_t* dev__8MQDuknW9cpR89cakjiYAXPg, NU8 reg__3q4TFB6wI6DiuvQJkNGbLg, NU8* val__8zJA0WAegaH46ePq8FmDRw) {	
#line 41 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
NI32 result;	
#line 42 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
tyArray__bN9bddWn8oiNSHn2MqEJSZQ buf;	
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
NI32 res;	nimfr_("i2c_read_reg", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");{	result = (NI32)0;	nimZeroMem((void*)buf, sizeof(tyArray__bN9bddWn8oiNSHn2MqEJSZQ));
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(43, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 43 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	res = i2c_dev_read_reg(dev__8MQDuknW9cpR89cakjiYAXPg, reg__3q4TFB6wI6DiuvQJkNGbLg, ((void*) ((&buf[(((NI)0))- 0]))), ((size_t)2));
#line 44 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(44, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");	{
#line 44 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 44 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		if (!!((res == ((NI32)0)))) goto LA3_;

#line 45 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(45, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 45 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		ESP_LOGD("I2CD", "Could not read from register 0x%02x", reg__3q4TFB6wI6DiuvQJkNGbLg);

#line 46 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(46, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 41 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(41, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 46 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(46, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");		result = res;		goto BeforeRet_;
	}
	LA3_: ;

#line 48 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(48, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 48 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 48 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 48 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	(*val__8zJA0WAegaH46ePq8FmDRw) = (NU8)((NU8)((NU32)(buf[(((NI)0))- 0]) << (NU32)(((NI)8))) | buf[(((NI)1))- 0]);
#line 49 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(49, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 41 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(41, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 49 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(49, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");	result = ((NI32)0);	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}

#line 51 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
N_LIB_PRIVATE N_NIMCALL(NI32, i2c_write_reg__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_69)(i2c_dev_t* dev__fxPb9aYKeWiTfGEyUpwvo4A, NU8 reg__h0yBmVABU0pWIYDYnFhj5g, NU8 val__7WD9cF17t69a31OP30wDRfiA) {	
#line 51 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
NI32 result;	
#line 52 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
tyArray__bN9bddWn8oiNSHn2MqEJSZQ buf;	
#line 53 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
NI32 res;	nimfr_("i2c_write_reg", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");{	result = (NI32)0;	nimZeroMem((void*)buf, sizeof(tyArray__bN9bddWn8oiNSHn2MqEJSZQ));
#line 52 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(52, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 52 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	buf[0] = (NU8)((NU8)(val__7WD9cF17t69a31OP30wDRfiA) >> (NU32)(((NI)8)));	buf[1] = val__7WD9cF17t69a31OP30wDRfiA;
#line 53 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(53, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 53 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	res = i2c_dev_write_reg(dev__fxPb9aYKeWiTfGEyUpwvo4A, reg__h0yBmVABU0pWIYDYnFhj5g, ((void*) ((&buf[(((NI)0))- 0]))), ((size_t)2));
#line 54 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(54, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");	{
#line 54 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"

#line 54 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		if (!!((res == ((NI32)0)))) goto LA3_;

#line 55 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(55, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 55 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		ESP_LOGD("I2CD", "Could not write 0x%04x to register 0x%02x", val__7WD9cF17t69a31OP30wDRfiA, reg__h0yBmVABU0pWIYDYnFhj5g);

#line 56 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(56, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 51 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(51, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 56 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
		nimln_(56, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");		result = res;		goto BeforeRet_;
	}
	LA3_: ;

#line 57 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(57, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 51 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(51, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 57 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(57, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");	result = ((NI32)0);	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();	return result;}
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnesperminus0dot6dot1minus1678fa54fffdd902a738b06dfb6bdabbfd2353c8atsnesperatsespminusidfminuslibatsi2cdev_utilsdotnim_Init000)(void) {

#line 999999 "generated_not_to_break_here"
{
NIM_BOOL* nimErr_;	nimfr_("i2cdev_utils", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");nimErr_ = nimErrorFlag();
#line 39 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	nimln_(39, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim");
#line 39 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/esp-idf-lib/i2cdev_utils.nim"
	i2cDeviceInit__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZesp45idf45libZi50cdev95utils_25();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	BeforeRet_: ;
	popFrame();}
}

