/* Generated by Nim Compiler v1.9.3 */
#define NIM_INTBITS 32

#include "nimbase.h"
#include <i2cdev.h>
#include "driver/i2c.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #define nimfrs_(proc, file, slots, length) \
    struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename;NI len;VarSlot s[slots];} FR_; \
    FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #define nimln_(n, file) \
    FR_.line = n; FR_.filename = file;
typedef struct tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w;
typedef struct tyObject_I2CDevConfig__2MJZG9b1Tsm60hG9bXtANqlg tyObject_I2CDevConfig__2MJZG9b1Tsm60hG9bXtANqlg;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef NI32 tyEnum_gpio_num_t__aEau6azTKd9bpnbBbGm9c9ccQ;
struct tyObject_I2CDevConfig__2MJZG9b1Tsm60hG9bXtANqlg {int port;
tyEnum_gpio_num_t__aEau6azTKd9bpnbBbGm9c9ccQ sda;
tyEnum_gpio_num_t__aEau6azTKd9bpnbBbGm9c9ccQ scl;
};
typedef NI32 tyEnum_i2c_mode_t__sAu6gHP6papa3cANrwGcyQ;
typedef NU8 tyArray__qtqsWM5aXmcpMIVmvq3kAA[16];
typedef NU8 tyArray__WplyaaK9a7ali8qLAFsJdKg[14];
struct tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w {i2c_dev_t device;
i2c_dev_t* device_ptr;
NU8 rate;
tyArray__qtqsWM5aXmcpMIVmvq3kAA buffer;
tyArray__WplyaaK9a7ali8qLAFsJdKg sensors;
NI gyro_range;
NI accel_range;
};
struct NimStrPayload {NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {NI len;
NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
typedef NF tyArray__AACV5tsODZUz7q0xBh9bP3A[7];
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size__LZn6dneMVUSD9cVJcoc7Slw, NI alignment__eu9b1Xf7SGvOM5v8REyXVWA);
N_LIB_PRIVATE N_NIMCALL(void, initDevice__OOZsrcZmpu54485348Zmpu54485348_862)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__CbSAqYObCdYW6l7zhwrUpw);
N_LIB_PRIVATE N_NIMCALL(void, app_main)(void);
N_NIMCALL(void, NimMain)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___main_77)(tyArray__AACV5tsODZUz7q0xBh9bP3A x__3gbgphmPr2YyFiVFGB9c3cA);
N_LIB_PRIVATE N_NIMCALL(void, readSensorsScaled__OOZsrcZmpu54485348Zmpu54485348_231)(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu6050__v4QYeTetDBAQ6n7UZ9c3tYg, tyArray__AACV5tsODZUz7q0xBh9bP3A Result);
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw);
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args__vU9bPv9cuTwXcj2blBSnzjTw, NI args__vU9bPv9cuTwXcj2blBSnzjTwLen_0);
N_LIB_PRIVATE N_NIMCALL(void, delay__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZtimers_213)(NU64 ts__DBbGsWe9bEjgDo5GtN3P9avA);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___stdZassertions_29)(NimStringV2* dest__C2JKGPCNdWKCPrsQvNywTQ);
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_4495)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnesperminus0dot6dot1minus1678fa54fffdd902a738b06dfb6bdabbfd2353c8atsnesperatsespatsdriveratsgpio_driverdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnesperminus0dot6dot1minus1678fa54fffdd902a738b06dfb6bdabbfd2353c8atsnesperatsespminusidfminuslibatsi2cdev_utilsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, atmdotdotatssrcatsmpu6050atsmpu6050_constsdotnim_Init000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);
N_LIB_PRIVATE tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* mpu__main_6;
N_LIB_PRIVATE NIM_CONST tyObject_I2CDevConfig__2MJZG9b1Tsm60hG9bXtANqlg i2cCfg__main_5 = {((int)0), ((tyEnum_gpio_num_t__aEau6azTKd9bpnbBbGm9c9ccQ)23), ((tyEnum_gpio_num_t__aEau6azTKd9bpnbBbGm9c9ccQ)22)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_4298;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;
extern NIM_THREADVAR TFrame* framePtr__system_3928;

#line 19 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimSetMem__systemZmemory_7)(void* a__tZiCJHYy5dYyAh9cxwrrVhQ, int v__iM7JOvZxArJIvbhGyRZG6Q, NI size__ntsFNLS0mpvnjQFrZT7DCw) {	void* T1_;
#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 21 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	T1_ = (void*)0;	T1_ = memset(a__tZiCJHYy5dYyAh9cxwrrVhQ, v__iM7JOvZxArJIvbhGyRZG6Q, ((size_t) (size__ntsFNLS0mpvnjQFrZT7DCw)));}

#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {	
#line 423 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
NIM_BOOL* result;	result = (NIM_BOOL*)0;
#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 424 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	result = (&nimInErrorMode__system_4298);	return result;}

#line 30 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
static N_INLINE(void, nimZeroMem)(void* p__BuPKoq7dppy2upaj3KUaxw, NI size__ttWVm79bajRU3tarcA7MkLw) {NIM_BOOL* nimErr_;{nimErr_ = nimErrorFlag();
#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"

#line 31 "/home/vincent/nim-1.9.3/nim/lib/system/memory.nim"
	nimSetMem__systemZmemory_7(p__BuPKoq7dppy2upaj3KUaxw, ((int)0), size__ttWVm79bajRU3tarcA7MkLw);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	}BeforeRet_: ;
}

#line 549 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, nimFrame)(TFrame* s__ZBM8FF7uw5z5eZuYXmXfaw) {
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 550 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!(framePtr__system_3928 == ((TFrame*) NIM_NIL))) goto LA3_;

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 551 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = ((NI16)0);	}
	goto LA1_;
	LA3_: ;
	{
#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 554 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		(*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth = (NI16)((*framePtr__system_3928).calldepth + ((NI16)1));	}
	LA1_: ;

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 556 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	(*s__ZBM8FF7uw5z5eZuYXmXfaw).prev = framePtr__system_3928;
#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 557 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = s__ZBM8FF7uw5z5eZuYXmXfaw;
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	{
#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		if (!((*s__ZBM8FF7uw5z5eZuYXmXfaw).calldepth == ((NI16)2000))) goto LA8_;

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 558 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
		callDepthLimitReached__system_4495();
	}
	LA8_: ;
}

#line 99 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
static N_INLINE(void, popFrame)(void) {
#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"

#line 100 "/home/vincent/nim-1.9.3/nim/lib/system/excpt.nim"
	framePtr__system_3928 = (*framePtr__system_3928).prev;}

#line 23 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
N_LIB_PRIVATE N_NIMCALL(void, app_main)(void) {NIM_BOOL* nimErr_;	nimfr_("app_main", "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");{nimErr_ = nimErrorFlag();
#line 24 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	nimln_(24, "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim");
#line 24 "/home/vincent/.nimble/pkgs2/nesper-0.6.1-1678fa54fffdd902a738b06dfb6bdabbfd2353c8/nesper/general.nim"
	NimMain();
	{
#line 22 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
		nimln_(22, "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim");		while (1) {			
#line 23 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
NimStringV2 colontmpD_;			tyArray__nHXaesL0DJZHyVS07ARPRA T4_;			tyArray__AACV5tsODZUz7q0xBh9bP3A T5_;			colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
#line 23 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
			nimln_(23, "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim");
#line 23 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"

#line 23 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"

#line 23 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"

#line 23 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
			nimZeroMem((void*)T5_, sizeof(tyArray__AACV5tsODZUz7q0xBh9bP3A));			readSensorsScaled__OOZsrcZmpu54485348Zmpu54485348_231(mpu__main_6, T5_);
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;
#line 23 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
			colontmpD_ = dollar___main_77(T5_);			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;			T4_[0] = colontmpD_;			echoBinSafe(T4_, 1);
#line 24 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
			nimln_(24, "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim");
#line 24 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
			delay__OOZOOZOOZOOZOOZOnimbleZpkgs50Znesper4548O54O494549545556fa5352fffdd574850a555156b4854dfb54bdabbfd50515351c56ZnesperZtimers_213(250ULL);
			if (NIM_UNLIKELY(*nimErr_)) goto LA3_;			{				LA3_:;			}
			{
#line 25 "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim"
				nimln_(25, "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim");
#line 25 "/home/vincent/nim-1.9.3/nim/lib/std/assertions.nim"
				eqdestroy___stdZassertions_29((&colontmpD_));
			}
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;		}
	}
	}BeforeRet_: ;
	popFrame();}

N_LIB_PRIVATE void PreMainInner(void) {
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnesperminus0dot6dot1minus1678fa54fffdd902a738b06dfb6bdabbfd2353c8atsnesperatsespatsdriveratsgpio_driverdotnim_Init000();
	atmdotdotatsdotdotatsdotdotatsdotdotatsdotdotatsdotnimbleatspkgs2atsnesperminus0dot6dot1minus1678fa54fffdd902a738b06dfb6bdabbfd2353c8atsnesperatsespminusidfminuslibatsi2cdev_utilsdotnim_Init000();
	atmdotdotatssrcatsmpu6050atsmpu6050_constsdotnim_Init000();
}

N_LIB_PRIVATE void PreMain(void) {
	#if 0
	void (*volatile inner)(void);
	inner = PreMainInner;
	(*inner)();
	#else
	PreMainInner();
	#endif
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	#if 0
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	(*inner)();
	#else
	PreMain();
	NimMainInner();
	#endif
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {

#line 999999 "generated_not_to_break_here"
{
	tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w* T1_;NIM_BOOL* nimErr_;	nimfr_("main", "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim");nimErr_ = nimErrorFlag();
#line 13 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
	nimln_(13, "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim");
#line 13 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
	T1_ = NIM_NIL;	T1_ = (tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w*) nimNewObj(sizeof(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w), NIM_ALIGNOF(tyObject_MPU6050DevicecolonObjectType___6NnSei1Aqal1UkYo9blHh2w));	(*T1_).rate = ((NU8)32);	(*T1_).gyro_range = ((NI)250);	(*T1_).accel_range = ((NI)2);	mpu__main_6 = T1_;
#line 19 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
	nimln_(19, "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim");
#line 19 "/home/vincent/Documents/Nim/MCU/NIMPU6050/main/main.nim"
	initDevice__OOZsrcZmpu54485348Zmpu54485348_862(mpu__main_6);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;	BeforeRet_: ;
	nimTestErrorFlag();	popFrame();}
}

